'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createServer}=require('../server.cjs'),P=require('../source/planner.cjs'),C=require('../source/core.js'),Session=require('../source/session.js');
async function fixture(fn,options={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'origin-test-'));const server=createServer({dataDir:dir,env:{},...options});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;try{const info=await (await fetch(base+'/api/bootstrap')).json();await fn({base,token:info.token,info,dir,post:(route,data,extra={})=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json','X-Origin-Token':info.token,'X-Jev-Provider':'openrouter',...extra},body:JSON.stringify(data)})});}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await fs.rm(dir,{recursive:true,force:true});}}
function plannerInput(){const w=C.genesis();return {mode:'agy',subject:C.perception(w,w.entities[0]),options:C.available(w,w.entities[0]).map(o=>({id:o.id,label:o.label,detail:o.detail}))};}
function proposal(){return {objective:'Hold an unfamiliar object',hypothesis:'A loose stone can be grasped',actions:['gather_stone'],expectedObservation:'One or more stones in this body\'s hands',evidence:[]};}

test('bootstrap never reveals configured API credentials',async()=>fixture(async({info})=>{assert.equal(info.hasJevKey,true);assert.ok(!JSON.stringify(info).includes('TEST_SERVER_SECRET_123'));},{env:{OPENROUTER_API_KEY:'TEST_SERVER_SECRET_123'}}));
test('cross-origin requests and wrong Host headers are rejected',async()=>fixture(async({base})=>{assert.equal((await fetch(base+'/api/bootstrap',{headers:{Origin:'https://attacker.invalid'}})).status,403);const status=await new Promise((resolve,reject)=>{require('node:http').get(base+'/api/bootstrap',{headers:{Host:'attacker.invalid'}},res=>{res.resume();resolve(res.statusCode);}).on('error',reject);});assert.equal(status,403);}));
test('model calls need a local session token',async()=>fixture(async({base})=>{assert.equal((await fetch(base+'/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);}));
test('private files and source paths are not served by the HTTP server',async()=>fixture(async({base})=>{for(const p of ['/.env','/data/latest.json','/server.cjs','/../server.cjs'])assert.equal((await fetch(base+p)).status,404);}));
test('Jev bridge forwards only to its fixed provider endpoint and redacts secrets',async()=>{let actual;await fixture(async({post})=>{const w=C.genesis(),res=await post('/api/jev',C.actionRequest(w,w.entities[0],'~typesafe/jev-latest'));assert.equal(res.status,200);const value=await res.json();assert.equal(value.echo,'[REDACTED]');assert.equal(actual.url,'https://openrouter.ai/api/alpha/decisions');assert.equal(actual.init.headers.Authorization,'Bearer TEST_SERVER_SECRET_123');},{env:{OPENROUTER_API_KEY:'TEST_SERVER_SECRET_123'},fetchImpl:async(url,init)=>{actual={url,init};return new Response(JSON.stringify({echo:'TEST_SERVER_SECRET_123'}),{status:200});}});});
test('server spending cap counts failed upstream attempts',async()=>fixture(async({post})=>{const w=C.genesis(),q=C.actionRequest(w,w.entities[0],'~typesafe/jev-latest');assert.equal((await post('/api/jev',q)).status,503);const r=await post('/api/jev',q);assert.match((await r.json()).error,/cap/);},{env:{OPENROUTER_API_KEY:'TEST_SERVER_SECRET_123',SERVER_JEV_CAP:'1'},fetchImpl:async()=>new Response('{"error":"test offline"}',{status:503})}));
test('checkpoints save and restore the full state but not server keys',async()=>fixture(async({post,base,token,dir})=>{const s=new Session(),snapshot=s.export();snapshot.log.push({text:'TEST_SERVER_SECRET_123'});const res=await post('/api/checkpoint',{snapshot});assert.equal(res.status,200);const loaded=await(await fetch(base+'/api/checkpoint',{headers:{'X-Origin-Token':token}})).json();assert.equal(loaded.world.entities.length,6);assert.ok(!JSON.stringify(loaded).includes('TEST_SERVER_SECRET_123'));assert.ok((await fs.stat(path.join(dir,'latest.json'))).isFile());},{env:{OPENROUTER_API_KEY:'TEST_SERVER_SECRET_123'}}));
test('planner contract rejects invented action IDs and fabricated evidence citations',()=>{assert.throws(()=>P.validateProposal({...proposal(),actions:['create_fire']},['gather_stone'],new Set()),/unavailable/);assert.throws(()=>P.validateProposal({...proposal(),evidence:['T99999']},['gather_stone'],new Set()),/outside/);});
test('planner input uses one subject without other people private memories',()=>{const input=plannerInput(),prompt=P.promptFor(input);assert.ok(!input.subject.visible_people.some(p=>p.memory||p.known));assert.ok(!prompt.includes('SKILLS='));assert.ok(prompt.includes('No tools'));});
test('AGY requires explicit server opt-in',async()=>{await assert.rejects(P.plan(plannerInput(),{env:{}}),/disabled/);});
test('AGY adapter accepts schema result while keeping it an unverified proposal',async()=>{const data=await P.plan(plannerInput(),{env:{AGY_ENABLED:'1'},runAgyImpl:async args=>{assert.equal(args.subject,'S01');return {result:{status:'SUCCESS',structured_output:proposal()},audit:{mode:'agy',model:'TEST_ONLY'}};}});assert.deepEqual(data.proposal.actions,['gather_stone']);});
test('cloud planner uses no tools, fixed endpoint and JSON schema with explicit model',async()=>{let q;const data=await P.plan({...plannerInput(),mode:'cloud',model:'provider/test-model'},{env:{PLANNER_API_KEY:'TEST_PLANNER_KEY'},fetchImpl:async(url,init)=>{assert.equal(url,'https://openrouter.ai/api/v1/chat/completions');q=JSON.parse(init.body);return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(proposal())}}]}));}});assert.equal(q.response_format.type,'json_schema');assert.equal(q.provider.require_parameters,true);assert.equal(q.tools,undefined);assert.equal(data.proposal.actions[0],'gather_stone');});
test('CLI child environment strips Jev and unrelated credential variables',()=>{const env=P.cleanEnv({PATH:'/test',OPENROUTER_API_KEY:'secret',AWS_SECRET_ACCESS_KEY:'secret',GEMINI_API_KEY:'own-model-key'});assert.equal(env.OPENROUTER_API_KEY,undefined);assert.equal(env.AWS_SECRET_ACCESS_KEY,undefined);assert.equal(env.GEMINI_API_KEY,'own-model-key');});

test('actual child-process adapter sends the prompt via stdin, without shell interpolation',async()=>{
 const {spawn}=require('node:child_process');let recorded;
 const payload=proposal();
 const program=`let s='';process.stdin.on('data',x=>s+=x);process.stdin.on('end',()=>{const m=JSON.parse(s);if(m.event!=='user'||!m.message.content.includes('safe test'))process.exit(3);console.log(JSON.stringify({event:'init',init:{tools:[]}}));console.log(JSON.stringify({event:'result',result:{status:'SUCCESS',structured_output:${JSON.stringify(payload)}}}));});`;
 const value=await P.runAgy({prompt:'safe test; not a shell command',schema:P.schemaFor(['gather_stone']),subject:'S01',env:{PATH:process.env.PATH,AGY_MODEL:'test-model',AGY_SANDBOX:'1'},spawnImpl:(cmd,args,opts)=>{recorded={cmd,args,opts};return spawn(process.execPath,['-e',program],opts);}});
 assert.equal(recorded.opts.shell,false);assert.ok(recorded.args.includes('--input-format'));assert.ok(recorded.args.includes('--sandbox'));assert.ok(!recorded.args.includes('safe test; not a shell command'));assert.notEqual(recorded.opts.cwd,path.resolve(__dirname,'..'));assert.equal(value.result.status,'SUCCESS');assert.equal(value.audit.events.length,2);
});
test('a CLI tool event is rejected and the child is stopped',async()=>{
 const {spawn}=require('node:child_process');
 const program="console.log(JSON.stringify({event:'step_update',step_update:{step_type:'tool',tool_name:'run_command'}}));setTimeout(()=>{},60000);";
 await assert.rejects(P.runAgy({prompt:'test',schema:P.schemaFor(['look']),subject:'S02',env:{PATH:process.env.PATH},spawnImpl:(cmd,args,opts)=>spawn(process.execPath,['-e',program],opts)}),/tool or subagent/);
});
test('agy 1.2.7 terminal finish tool carries the structured result and is accepted; other tools are not',async()=>{
 const {spawn}=require('node:child_process'),out={ok:true};
 const run=events=>P.runAgy({prompt:'test',schema:P.schemaFor(['look']),subject:'S02',env:{PATH:process.env.PATH},spawnImpl:(cmd,args,opts)=>spawn(process.execPath,['-e',`for(const e of ${JSON.stringify(events)})console.log(JSON.stringify(e));`],opts)});
 const finishTool={event:'step_update',step_update:{step_index:2,state:'ACTIVE',step_type:'tool',tool_name:'finish',tool_info:{name:'finish',parameters:out}}};
 const tail=[{event:'step_update',step_update:{step_index:2,state:'DONE',step_type:'finish'}},{event:'result',result:{status:'SUCCESS',response:JSON.stringify(out),structured_output:out}}];
 const {result}=await run([finishTool,...tail]);assert.deepEqual(result.structured_output,out);
 await assert.rejects(run([{...finishTool,step_update:{...finishTool.step_update,tool_info:{name:'run_command'}}},...tail]),/tool or subagent/);
 await assert.rejects(run([{...finishTool,step_update:{...finishTool.step_update,subagent_info:{id:'x'}}},...tail]),/tool or subagent/);
});
