'use strict';
const assert=require('node:assert/strict'),C=require('../source/core.js'),Session=require('../source/session.js');
const tests=[],originalFetch=global.fetch;let calls=[];
function responseFor(req,choose={}){return {model:'typesafe/jev-1.13',answers:Object.fromEntries(Object.entries(req.questions).map(([id,q])=>{const key=choose[id]||Object.keys(q.criteria)[0];return [id,{type:'choice',choice:key,confidence:.92,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===key?1:0]))}];})),usage:{input_tokens:42,output_tokens:0}};}
function fake(handler){calls=[];global.fetch=async(url,init)=>{const req=JSON.parse(init.body);calls.push({url,init,req});const n=calls.length;const body=await handler(req,n);return {ok:body?._http?false:true,status:body?._http||200,statusText:'Test response',headers:new Headers(),text:async()=>JSON.stringify(body)};};}
function sess(cap=100){const s=new Session({canExecute:()=>true});s.connect('test-only-secret-not-real',{cap,hierarchical:false});s.config.gap=0;return s;}
async function test(name,fn){try{await fn();tests.push({name,passed:true});console.log('PASS',name);}catch(e){tests.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}}
(async()=>{
await test('Genesis contains no learned abilities, relationships, vocabulary or carried resources',()=>{const w=C.genesis();assert.equal(w.tick,0);for(const a of w.entities){assert.deepEqual(a.known,{});assert.deepEqual(a.lexicon,{});assert.deepEqual(a.relationships,{});assert.equal(a.memory.length,0);assert.ok(Object.values(a.inventory).every(v=>v===0));}});
await test('Disconnected step makes zero requests and leaves the entire world unchanged',async()=>{fake(()=>{throw Error('Must not be reached');});const s=new Session(),before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(calls.length,0);assert.equal(C.fingerprint(s.world),before);});
await test('No timer advances an unconnected world',async()=>{const s=new Session(),before=C.fingerprint(s.world);await new Promise(r=>setTimeout(r,40));assert.equal(C.fingerprint(s.world),before);});
await test('Non-Jev identity, unknown option, missing distribution and wrong sums are rejected',()=>{const req=C.actionRequest(C.genesis(),C.genesis().entities[0],'~typesafe/jev-latest');const b=responseFor(req);for(const mutate of [x=>x.model='other/chat',x=>x.answers.action.choice='fake',x=>delete x.answers.action.probabilities,x=>x.answers.action.probabilities.rest=.1,x=>x.answers.action.confidence=-.2]){const v=C.clone(b);mutate(v);assert.throws(()=>C.validResponse(v,req));}});
await test('A valid typed Jev response commits exactly one action and advances one world turn',async()=>{fake(req=>responseFor(req,{action:'gather_food'}));const s=sess();assert.equal(await s.step(),true);assert.equal(calls.length,1);assert.equal(s.world.tick,1);assert.equal(s.world.entities[0].inventory.food,3);assert.equal(s.world.resources.food,87);assert.equal(s.world.cursor,1);assert.equal(s.log.filter(r=>r.type==='commit').length,1);assert.equal(s.log.find(r=>r.type==='request').committed,true);});
await test('HTTP authentication failure produces no world changes and no automatic retry',async()=>{fake(()=>({_http:401,error:{message:'Invalid API key'}}));const s=sess(),before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(s.attempts,1);assert.equal(calls.length,1);assert.equal(C.fingerprint(s.world),before);assert.match(s.error,/401/);});
await test('Malformed success answer cannot trigger a fallback',async()=>{fake(()=>({model:'typesafe/jev-1.13',answers:{}}));const s=sess(),before=C.fingerprint(s.world);await s.step();assert.equal(C.fingerprint(s.world),before);assert.equal(calls.length,1);assert.equal(s.world.cumulative.actions,0);});
await test('Failed learning phase rolls back the entire uncommitted physical experiment',async()=>{fake((req,n)=>n===1?responseFor(req,{action:'try_stone'}):({_http:503,error:{message:'Unavailable'}}));const s=sess();s.world.entities[0].inventory.stone=3;const before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(C.fingerprint(s.world),before);assert.equal(calls.length,2);assert.equal(s.log.filter(r=>r.type==='request'&&r.committed).length,0);});
await test('Request cap freezes a multi-phase turn with no partial resource changes',async()=>{fake(req=>responseFor(req,{action:'try_stone'}));const s=sess(1);s.world.entities[0].inventory.stone=3;const before=C.fingerprint(s.world);await s.step();assert.equal(s.attempts,1);assert.equal(calls.length,1);assert.equal(C.fingerprint(s.world),before);assert.equal(s.status,'limited');assert.match(s.phase,/request limit/);});
await test('Receiver independently accepts an offer; total food is conserved',async()=>{fake((req,n)=>responseFor(req,n===1?{action:'share_S02'}:{response:'accept'}));const s=sess();s.world.entities[0].inventory.food=2;assert.equal(await s.step(),true);assert.equal(calls.length,2);assert.equal(calls[1].req.state.subject.subject,'S02');assert.equal(s.world.entities[0].inventory.food,1);assert.equal(s.world.entities[1].inventory.food,1);assert.equal(s.world.entities[1].relationships.S01,8);assert.ok(s.world.entities[1].memory.length);});
await test('A Jev refusal causes no inventory transfer',async()=>{fake((req,n)=>responseFor(req,n===1?{action:'share_S02'}:{response:'decline'}));const s=sess();s.world.entities[0].inventory.food=2;await s.step();assert.equal(s.world.entities[0].inventory.food,2);assert.equal(s.world.entities[1].inventory.food,0);});
await test('Receiver gets observable token and gesture, never the current intended referent',async()=>{fake((req,n)=>responseFor(req,n===1?{action:'signal_S02'}:n===2?{referent:'water',token:'ka',gesture:'point_water'}:{attention:'attend',interpretation:'food'}));const s=sess();assert.equal(await s.step(),true);assert.equal(calls.length,3);assert.equal(calls[2].req.state.incoming.token,'ka');assert.ok(!('referent' in calls[2].req.state.incoming));assert.ok(!('intended' in calls[2].req.state.incoming));assert.equal(s.world.language[0].intended,'water');assert.equal(s.world.language[0].interpreted,'food');assert.equal(s.world.entities[1].lexicon.ka.food,1);assert.equal(s.world.entities[1].lexicon.ka.water,undefined);assert.equal(s.world.cumulative.misunderstandings,1);assert.deepEqual(s.world.entities[1].known,{});});
await test('Successful experiment plus supported Jev inference gives only the learner a skill',async()=>{fake((req,n)=>responseFor(req,n===1?{action:'try_stone'}:{inference:'supported'}));const s=sess();const a=s.world.entities[0];a.inventory.stone=3;a.trials.stone=1;await s.step();assert.ok(s.world.entities[0].known.stone);assert.ok(s.world.entities.slice(1).every(a=>!a.known.stone));assert.equal(s.world.entities[0].inventory.stone,2);});
await test('Unsupported experiment cannot grant a skill even when Jev chooses supported',async()=>{fake((req,n)=>responseFor(req,n===1?{action:'try_stone'}:{inference:'supported'}));const s=sess();s.world.entities[0].inventory.stone=3;await s.step();assert.equal(s.world.entities[0].trials.stone,1);assert.equal(s.world.entities[0].known.stone,undefined);});
await test('A burning fire warms nearby others and loses finite fuel only on committed turns',async()=>{fake(req=>responseFor(req,{action:'light_fire'}));const s=sess();s.world.entities[0].known.fire={evidence:'fixture',turn:0};s.world.entities[0].inventory.wood=2;const warmth=s.world.entities[1].body.warmth;await s.step();assert.ok(s.world.entities[1].body.warmth>warmth);assert.equal(s.world.fire.fuel,23);assert.equal(s.world.entities[0].inventory.wood,0);});
await test('Learning prerequisites block fire, metalworking and writing at genesis',()=>{const w=C.genesis(),opts=C.available(w,w.entities[0]);for(const id of ['try_fire','light_fire','try_metallurgy','try_writing','build_shelter'])assert.ok(!opts.some(o=>o.id===id));});
await test('Confidence gate rejects the whole turn without human override or local choice',async()=>{fake(req=>{const b=responseFor(req,{action:'gather_food'});b.answers.action.confidence=.1;return b;});const s=sess();s.config.gate=.35;const before=C.fingerprint(s.world);await s.step();assert.equal(C.fingerprint(s.world),before);assert.match(s.error,/confidence/);});
await test('Pause discards a late response even if a transport ignores cancellation',async()=>{let release;fake(req=>new Promise(r=>release=()=>r(responseFor(req,{action:'gather_food'}))));const s=sess(),before=C.fingerprint(s.world);const work=s.step();await new Promise(r=>setTimeout(r,10));s.pause();release();await work;assert.equal(C.fingerprint(s.world),before);assert.equal(s.log.filter(r=>r.type==='commit').length,0);});
await test('Exports never serialize the personal API key',async()=>{fake(req=>responseFor(req,{action:'rest'}));const s=sess();await s.step();const text=JSON.stringify(s.export());assert.ok(!text.includes('test-only-secret-not-real'));assert.ok(!text.includes('Authorization'));assert.ok(text.includes('probabilities'));});
await test('World reset does not reset request usage or erase historical receipts',async()=>{fake(req=>responseFor(req,{action:'rest'}));const s=sess();await s.step();const count=s.log.length;s.reset();assert.equal(s.attempts,1);assert.equal(s.world.tick,0);assert.ok(s.log.length>count);});
await test('A hidden page or missing renderer makes no paid API call',async()=>{fake(()=>{throw Error('No network should be used');});const s=new Session({canExecute:()=>false});s.connect('test-only-secret-not-real');const before=C.fingerprint(s.world);await s.step();assert.equal(calls.length,0);assert.equal(C.fingerprint(s.world),before);});
await test('Every committed turn references its complete set of Jev request receipts',async()=>{fake((req,n)=>responseFor(req,n===1?{action:'signal_S02'}:n===2?{referent:'water',token:'mu',gesture:'point_water'}:{attention:'attend',interpretation:'water'}));const s=sess();await s.step();const event=s.log.find(r=>r.type==='commit');assert.equal(event.receipts.length,3);assert.deepEqual(s.world.lastCommit.receipts,event.receipts);assert.equal(s.world.language[0].token,'mu');});
global.fetch=originalFetch;require('node:fs').writeFileSync(require('node:path').join(__dirname,'../validation/legacy-core-results.json'),JSON.stringify({testedAt:new Date().toISOString(),method:'Node.js unit and integration tests. API responses are explicit test fixtures, not live provider responses. No test policy is shipped in the application.',passed:tests.filter(t=>t.passed).length,total:tests.length,tests},null,2));if(tests.some(t=>!t.passed))process.exitCode=1;
})();
