'use strict';
// Native API contract tests. Every upstream response below is an explicit TEST FIXTURE.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const P=require('../source/providers.js'),C=require('../source/core.js'),Session=require('../source/session.js'),Planner=require('../source/planner.cjs');
const {createServer}=require('../server.cjs');
const KEY='TEST_TYPESAFE_SECRET_ONLY',ORKEY='TEST_OPENROUTER_SECRET_ONLY';
function answers(q,choice={}){return {model:'jev-1.13.0',answers:Object.fromEntries(Object.entries(q.questions).map(([k,v])=>{const c=choice[k]||Object.keys(v.criteria)[0];return [k,{type:'choice',choice:c,probabilities:Object.fromEntries(Object.keys(v.criteria).map(id=>[id,id===c?1:0])),confidence:.93}];})),usage:{input_tokens:10,output_tokens:2}};}
async function mock(fn,run){const old=global.fetch;global.fetch=fn;try{await run();}finally{global.fetch=old;}}
async function serverTest(fn,options={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'origin-native-')),server=createServer({env:{TYPESAFE_API_KEY:KEY},dataDir:dir,...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{const info=await(await fetch(base+'/api/bootstrap')).json();await fn({base,info,post:(route,body={},extra={})=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json','X-Origin-Token':info.token,...extra},body:JSON.stringify(body)})});}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await fs.rm(dir,{recursive:true,force:true});}}
function q(model='jev-latest'){const w=C.genesis();return C.actionRequest(w,w.entities[0],model);}

test('new sessions default to native TypeSafe with native model ID',()=>{const s=new Session();assert.equal(s.config.provider,'typesafe');assert.equal(s.config.model,'jev-latest');assert.equal(s.url,'https://api.typesafe.ai/v1/systemone');assert.equal(s.config.planner,'none');});
test('native API contract accepts official alias, preview and pinned native IDs only',()=>{for(const m of ['jev-latest','jev-preview','jev-1.13.0'])assert.equal(P.validateModel('typesafe',m),m);assert.throws(()=>P.validateModel('typesafe','~typesafe/jev-latest'),/Invalid TypeSafe/);assert.throws(()=>P.validateModel('typesafe','typesafe/jev-1.13'),/Invalid TypeSafe/);assert.throws(()=>P.get('__proto__'),/Unknown/);});
test('an OpenRouter server key cannot satisfy a missing TypeSafe key',()=>{const s=new Session();s.setBridge('TEST_LOCAL_TOKEN',{hasJevKey:true,hasOpenRouterKey:true,hasTypeSafeKey:false});assert.throws(()=>s.connect('',{transport:'bridge'}),/TYPESAFE_API_KEY/);assert.equal(s.connected,false);});
test('native server key needs no OpenRouter key and is not present in the browser session',()=>{const s=new Session();s.setBridge('TEST_LOCAL_TOKEN',{hasJevKey:true,hasTypeSafeKey:true});s.connect('',{transport:'bridge'});assert.equal(s.connected,true);assert.equal(s.config.provider,'typesafe');assert.ok(!JSON.stringify(s.export()).includes(KEY));});
test('native key is trimmed, kept only in memory, and never written to snapshots',()=>{const s=new Session();s.connect('  '+KEY+'  ');assert.ok(!JSON.stringify(s.export()).includes(KEY));assert.throws(()=>s.connect('sk-or-v1-wrong-provider'),/OpenRouter key/);assert.throws(()=>P.keyFor('typesafe','key\nheader'),/Invalid API/);});
test('standalone native decision actually targets TypeSafe, using Bearer auth and native model',async()=>{const calls=[];await mock(async(url,init)=>{calls.push({url,init});const req=JSON.parse(init.body);return Response.json(answers(req,{intent:'manipulate',action:'gather_stone'}));},async()=>{const s=new Session({canExecute:()=>true});s.connect(KEY);s.config.gap=0;assert.equal(await s.step(),true);assert.equal(s.world.tick,1);assert.equal(calls.length,2);for(const call of calls){assert.equal(call.url,P.get('typesafe').endpoint);assert.equal(call.init.headers.Authorization,'Bearer '+KEY);assert.equal(JSON.parse(call.init.body).model,'jev-latest');assert.equal(call.init.redirect,'error');}assert.equal(s.world.entities[0].inventory.stone,4);assert.ok(s.log.filter(r=>r.type==='request').every(r=>r.provider==='typesafe'&&r.upstreamEndpoint===P.get('typesafe').endpoint));assert.ok(!JSON.stringify(s.export()).includes(KEY));});});
test('native pinned model survives connection instead of being silently overwritten',()=>{const s=new Session();s.connect(KEY,{model:'jev-1.13.0'});assert.equal(s.config.model,'jev-1.13.0');});
test('native TypeSafe model ID is accepted by typed response validation',()=>assert.doesNotThrow(()=>C.validResponse(answers(q()),q())));
test('TypeSafe 401 freezes the entire turn without a provider fallback',async()=>{let count=0;await mock(async()=>{count++;return Response.json({detail:'invalid token'},{status:401});},async()=>{const s=new Session({canExecute:()=>true});s.connect(KEY);const before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(C.fingerprint(s.world),before);assert.equal(count,1);assert.match(s.error,/TypeSafe HTTP 401/);assert.match(s.error,/TYPESAFE_API_KEY/);assert.equal(s.attempts,1);});});
test('native 422 detail arrays become actionable text while exact body stays in ledger',async()=>{const detail=[{loc:['body','questions','action'],msg:'invalid criteria'}];await mock(async()=>Response.json({detail},{status:422}),async()=>{const s=new Session({canExecute:()=>true});s.connect(KEY);assert.equal(await s.step(),false);assert.match(s.error,/body.questions.action: invalid criteria/);assert.deepEqual(s.log.find(r=>r.type==='request').response.detail,detail);assert.equal(s.world.tick,0);});});
test('native 529 is not auto-retried and preserves Retry-After metadata',async()=>{let n=0;await mock(async()=>{n++;return Response.json({detail:'overloaded'},{status:529,headers:{'retry-after':'7'}});},async()=>{const s=new Session({canExecute:()=>true});s.connect(KEY);await s.step();assert.equal(n,1);assert.equal(s.world.tick,0);assert.ok(s.retryNotBefore>Date.now()+5000);assert.equal(s.log.find(r=>r.type==='request').retryAfter,'7');});});
test('native account access test makes GET models only, leaves decisions and world unchanged',async()=>{let call;await mock(async(url,init)=>{call={url,init};return Response.json({models:[{name:'jev-latest'}]});},async()=>{const s=new Session(),before=C.fingerprint(s.world);assert.deepEqual(await s.testTypeSafeConnection(KEY),['jev-latest']);assert.equal(call.url,'https://api.typesafe.ai/v1/models');assert.equal(call.init.method,'GET');assert.equal(call.init.body,undefined);assert.equal(call.init.headers.Authorization,'Bearer '+KEY);assert.equal(s.attempts,0);assert.equal(s.connected,false);assert.equal(C.fingerprint(s.world),before);assert.equal(s.log.find(r=>r.type==='connection_check').status,'valid');assert.ok(!JSON.stringify(s.export()).includes(KEY));});});
test('failed account checks cannot leak a key echoed by the provider',async()=>mock(async()=>Response.json({error:'invalid '+KEY},{status:401}),async()=>{const s=new Session();await assert.rejects(s.testTypeSafeConnection(KEY),/TypeSafe HTTP 401/);assert.equal(s.attempts,0);assert.ok(!JSON.stringify(s.export()).includes(KEY));assert.equal(s.busy,false);}));
test('account checks bypass renderer dependency without starting any simulation',async()=>mock(async()=>Response.json({models:[]}),async()=>{const s=new Session({canExecute:()=>false});await s.testTypeSafeConnection(KEY);assert.equal(s.world.tick,0);assert.equal(s.attempts,0);}));
test('native bridge advertises provider-specific credentials, never their values',async()=>serverTest(async({info})=>{assert.equal(info.defaultProvider,'typesafe');assert.equal(info.defaultModel,'jev-latest');assert.equal(info.hasTypeSafeKey,true);assert.equal(info.hasOpenRouterKey,false);assert.equal(info.cloudEnabled,false);assert.ok(!JSON.stringify(info).includes(KEY));}));
test('native bridge routes to TypeSafe by default without touching OpenRouter',async()=>{let call;await serverTest(async({post})=>{const res=await post('/api/jev',q());assert.equal(res.status,200);assert.equal(res.headers.get('x-origin-provider'),'typesafe');assert.equal(call.url,'https://api.typesafe.ai/v1/systemone');assert.equal(call.init.headers.Authorization,'Bearer '+KEY);assert.equal(call.init.redirect,'error');assert.equal(JSON.parse(call.init.body).model,'jev-latest');},{fetchImpl:async(url,init)=>{call={url,init};return Response.json(answers(JSON.parse(init.body)));}});});
test('native and legacy keys stay isolated when both are configured',async()=>{const calls=[];await serverTest(async({post})=>{await post('/api/jev',q());await post('/api/jev',q('~typesafe/jev-latest'),{'X-Jev-Provider':'openrouter'});assert.equal(calls[0].key,'Bearer '+KEY);assert.equal(calls[0].url,P.get('typesafe').endpoint);assert.equal(calls[1].key,'Bearer '+ORKEY);assert.equal(calls[1].url,P.get('openrouter').endpoint);},{env:{TYPESAFE_API_KEY:KEY,OPENROUTER_API_KEY:ORKEY},fetchImpl:async(url,init)=>{calls.push({url,key:init.headers.Authorization});return Response.json(answers(JSON.parse(init.body)));}});});
test('wrong native/legacy model is rejected before any upstream call',async()=>{let calls=0;await serverTest(async({post})=>{const res=await post('/api/jev',q('~typesafe/jev-latest'));assert.equal(res.status,400);assert.match((await res.json()).error,/Invalid TypeSafe model/);assert.equal(calls,0);},{fetchImpl:async()=>{calls++;throw Error('unexpected');}});});
test('missing native key cannot silently fall back to configured OpenRouter credential',async()=>{let calls=0;await serverTest(async({post})=>{const res=await post('/api/jev',q());assert.equal(res.status,401);assert.match((await res.json()).error,/TYPESAFE_API_KEY/);assert.equal(calls,0);},{env:{OPENROUTER_API_KEY:ORKEY},fetchImpl:async()=>{calls++;throw Error('unexpected');}});});
test('native bridge propagates upstream 429 and Retry-After without auto retry',async()=>{let calls=0;await serverTest(async({post})=>{const res=await post('/api/jev',q());assert.equal(res.status,429);assert.equal(res.headers.get('retry-after'),'9');assert.equal(calls,1);},{fetchImpl:async()=>{calls++;return Response.json({detail:'slow down'},{status:429,headers:{'retry-after':'9','x-request-id':'native-test-id'}});}});});
test('native bridge model-list test uses server TypeSafe key and no decision allowance',async()=>{let call;await serverTest(async({post,base,info})=>{const res=await post('/api/jev-models');assert.equal(res.status,200);assert.equal(call.url,'https://api.typesafe.ai/v1/models');assert.equal(call.init.method,'GET');assert.equal(call.init.body,undefined);const boot=await(await fetch(base+'/api/bootstrap')).json();assert.equal(boot.jevAttempts,0);assert.equal(boot.connectionChecks,1);assert.equal((await fetch(base+'/api/jev-models',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);},{fetchImpl:async(url,init)=>{call={url,init};return Response.json({models:[{name:'jev-latest'}]});}});});
test('ephemeral pasted TypeSafe key is also redacted from bridge exceptions',async()=>{const ephemeral='TEST_PASTED_NATIVE_KEY';await serverTest(async({post})=>{const res=await post('/api/jev',q(),{Authorization:'Bearer '+ephemeral});const data=await res.json();assert.ok(!JSON.stringify(data).includes(ephemeral));assert.match(data.error,/REDACTED/);},{env:{},fetchImpl:async()=>{throw Error('unexpected echo '+ephemeral);}});});
test('native-only environment cannot authenticate optional OpenRouter planner',async()=>{const w=C.genesis(),a=w.entities[0];await assert.rejects(Planner.plan({mode:'cloud',model:'test/model',subject:C.perception(w,a),options:C.available(w,a)},{env:{TYPESAFE_API_KEY:KEY},fetchImpl:async()=>{throw Error('unexpected');}}),/PLANNER_API_KEY|OPENROUTER_API_KEY/);assert.equal(Planner.cleanEnv({TYPESAFE_API_KEY:KEY}).TYPESAFE_API_KEY,undefined);});
