'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../source/core.js'),Session=require('../source/session.js');
function answer(req,choices={}){return {model:'typesafe/jev-1.13-test-fixture',answers:Object.fromEntries(Object.entries(req.questions).map(([key,q])=>{const chosen=choices[key]||Object.keys(q.criteria)[0];return [key,{type:'choice',choice:chosen,probabilities:Object.fromEntries(Object.keys(q.criteria).map(id=>[id,id===chosen?1:0])),confidence:.95}];})),usage:{input_tokens:10,output_tokens:1}};}
async function withMock(fn,run){const old=global.fetch,calls=[];global.fetch=async(url,init)=>{const req=JSON.parse(init.body);calls.push({url,req,init});const body=await fn(req,calls.length,url);return new Response(JSON.stringify(body),{status:200,headers:{'Content-Type':'application/json'}});};try{await run(calls);}finally{global.fetch=old;}}
function session(opts={}){const s=new Session({canExecute:()=>true});s.connect('TEST_ONLY_NOT_AN_API_KEY',{cap:1000,...opts});s.config.gap=0;return s;}
function commit(w,action,who='S01',decisions={}){const a=C.byId(w,who),o=C.available(w,a).find(o=>o.id===action);assert.ok(o,'available action '+action);const draft=C.clone(w);const r=C.rawAction(draft,C.byId(draft,who),o,decisions);return C.commitDraft(w,draft,who,r,['TEST_FIXTURE']);}

test('look observes in place for all six subjects; no forced gathering at camp',()=>{for(const a of C.genesis().entities){const w=C.genesis(),b=C.byId(commit(w,'look',a.id),a.id);assert.equal(b.x,a.x);assert.equal(b.z,a.z);}});
test('rest also stays in place unless a named shelter is chosen',()=>{const w=C.genesis();w.entities[0].x=12;w.entities[0].z=1;const after=commit(w,'rest');assert.equal(after.entities[0].x,12);assert.equal(after.entities[0].z,1);});
test('first observation records concrete facts; unchanged repeats are marked low-information',()=>{let w=C.genesis();w=commit(w,'look');assert.equal(w.entities[0].behavior.lastOutcome.new_scene_facts,true);w=commit(w,'look');assert.equal(w.entities[0].behavior.lastOutcome.new_scene_facts,false);assert.equal(w.entities[0].behavior.stagnant,1);assert.equal(Object.keys(w.entities[0].observations).length,1);});
test('scene novelty ignores clock ticks but notices another visible person moving',()=>{let w=commit(C.genesis(),'look');assert.equal(C.behaviorReport(w,w.entities[0]).scene_has_unrecorded_facts,false);w.entities[1].x+=2;assert.equal(C.behaviorReport(w,w.entities[0]).scene_has_unrecorded_facts,true);});
test('an explicitly chosen inspection moves to its specific location',()=>{const w=commit(C.genesis(),'inspect_grove');assert.ok(C.dist(w.entities[0],C.SITES.grove)<2);assert.ok(w.entities[0].observations.grove);assert.equal(w.entities[0].inventory.food,0);});
test('Jev chooses intention before action and both receipts are committed',async()=>withMock(req=>answer(req,{intent:'manipulate',action:'gather_stone'}),async calls=>{const s=session();assert.equal(await s.step(),true);assert.equal(calls.length,2);assert.ok(calls[0].req.questions.intent);assert.equal(calls[1].req.state.subject.active_intent.id,'manipulate');assert.equal(s.world.entities[0].intent.id,'manipulate');assert.equal(s.world.entities[0].inventory.stone,4);assert.equal(s.world.lastCommit.receipts.length,2);}));
test('intent persists for three personal turns without a new goal API call',async()=>withMock(req=>answer(req,{intent:'nourish',action:'gather_food'}),async calls=>{const s=session();for(let i=0;i<13;i++)assert.equal(await s.step(),true);assert.equal(calls.filter(c=>c.req.questions.intent).length,6);assert.equal(s.world.entities[0].completed,3);}));
test('failure after a staged Jev intention does not mutate intent or body',async()=>withMock((req,n)=>n===1?answer(req,{intent:'connect'}):{model:'typesafe/jev-1.13',answers:{}},async()=>{const s=session(),before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(C.fingerprint(s.world),before);assert.ok(s.log.find(r=>r.type==='request'&&r.status==='valid'&&!r.committed));}));
test('forced repeated look responses stop spending at STALLED instead of looping forever',async()=>withMock(req=>answer(req,{intent:'investigate',action:'look'}),async calls=>{const s=session();await s.start();assert.equal(s.status,'stalled');assert.equal(s.world.tick,19);assert.ok(s.log.some(r=>r.type==='stagnation'));assert.equal(s.world.entities[0].behavior.stagnant,3);const n=calls.length;await new Promise(r=>setTimeout(r,25));assert.equal(calls.length,n);assert.ok(s.world.entities.every(a=>!Object.values(a.inventory).some(Boolean)));}));
test('new useful action resets the individual low-information streak',()=>{let w=C.genesis();for(let i=0;i<3;i++)w=commit(w,'look');assert.equal(w.entities[0].behavior.stagnant,2);w=commit(w,'gather_stone');assert.equal(w.entities[0].behavior.stagnant,0);});
test('nearby witnesses remember visible action but never inherit private knowledge',()=>{const w=commit(C.genesis(),'rest');assert.ok(w.entities[1].memory.some(m=>m.kind==='witness'));assert.deepEqual(w.entities[1].known,{});assert.equal(w.entities[1].intent,null);});
test('remote subjects do not receive a private witness memory',()=>{const w=C.genesis();w.entities[1].x=35;const after=commit(w,'rest');assert.equal(after.entities[1].memory.length,0);});
test('plan is staged, shown to Jev, and cannot itself execute an action',async()=>withMock((req,n,url)=>url==='/api/plan'?{proposal:{objective:'Test this stone',hypothesis:'Striking changes it',actions:['gather_stone'],expectedObservation:'A held stone',evidence:[]},audit:{model:'TEST_PLANNER'}}:answer(req,{intent:'manipulate',action:'look'}),async calls=>{const s=new Session({canExecute:()=>true});s.setBridge('LOCAL_TEST_TOKEN',{hasJevKey:true,hasTypeSafeKey:true});s.connect('',{transport:'bridge',planner:'agy'});s.config.gap=0;assert.equal(await s.step(),true);assert.equal(s.world.entities[0].inventory.stone,0);assert.equal(s.world.entities[0].last.id,'look');assert.equal(s.world.entities[0].proposal.source,'agy');assert.ok(calls.find(c=>c.req.questions?.action).req.state.subject.unverified_planner_proposal);}));
test('unavailable planner action is rejected before any Jev request or world mutation',async()=>withMock(()=>({proposal:{objective:'Invent',actions:['unlock_all']}}),async calls=>{const s=new Session({canExecute:()=>true});s.setBridge('LOCAL_TEST_TOKEN',{hasJevKey:true,hasTypeSafeKey:true});s.connect('',{transport:'bridge',planner:'agy'});const before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(calls.length,1);assert.equal(C.fingerprint(s.world),before);}));
test('explicit pause reason is preserved in the rejected request and ledger',async()=>withMock(async req=>{await new Promise(r=>setTimeout(r,15));return answer(req);},async()=>{const s=session(),step=s.step();setTimeout(()=>s.pause('Tab hidden; execution paused.'),2);await step;assert.ok(s.log.some(r=>r.type==='pause'&&r.text==='Tab hidden; execution paused.'));assert.match(s.log.find(r=>r.type==='request').error,/Tab hidden/);assert.equal(s.world.tick,0);}));
test('restoring a checkpoint restores full history but no credentials or automatic execution',async()=>withMock(req=>answer(req,{intent:'nourish',action:'gather_food'}),async()=>{const a=session();await a.step();const snapshot=a.export();const b=new Session();b.restore(snapshot);assert.equal(b.world.tick,1);assert.equal(b.connected,false);assert.equal(b.running,false);assert.ok(b.log.some(r=>r.type==='commit'));assert.ok(b.log[0].provenance);assert.ok(!JSON.stringify(snapshot).includes('TEST_ONLY_NOT_AN_API_KEY'));}));
test('browser bridge token is excluded from exported checkpoints',()=>{const s=new Session();s.setBridge('PRIVATE_LOCAL_TOKEN',{hasJevKey:true,hasTypeSafeKey:true});s.connect('',{transport:'bridge'});assert.ok(!JSON.stringify(s.export()).includes('PRIVATE_LOCAL_TOKEN'));});
