'use strict';
// All generated model responses in this file are explicit test fixtures.
// Recorded v4 replay uses the user's supplied records, never a new provider call.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../source/core.js'),Session=require('../source/session.js');
function answer(req,choices={}){return {model:'typesafe/jev-test-fixture',answers:Object.fromEntries(Object.entries(req.questions).map(([k,q])=>{const chosen=choices[k]||Object.keys(q.criteria)[0];return [k,{type:'choice',choice:chosen,confidence:.96,probabilities:Object.fromEntries(Object.keys(q.criteria).map(o=>[o,o===chosen?1:0]))}];}))};}
async function fixture(respond,run){const old=global.fetch,calls=[];global.fetch=async(url,init)=>{const req=JSON.parse(init.body);calls.push(req);const data=await respond(req,calls.length);return new Response(JSON.stringify(data),{status:200});};try{await run(calls);}finally{global.fetch=old;}}
function session(options={}){const s=new Session({canExecute:()=>true});s.connect('TEST_CREDENTIAL_ONLY',{cap:200,...options});s.config.gap=0;return s;}
function act(w,id,who='S01'){const d=C.clone(w),a=C.byId(d,who),o=C.available(d,a).find(o=>o.id===id);assert.ok(o,id+' must be available');const result=C.rawAction(d,a,o,{});return {world:C.commitDraft(w,d,who,result,['EXPLICIT_TEST_FIXTURE']),result};}

test('the uploaded v4 journal replays with all 74 exact commit diffs',()=>{
 const V4=require('./fixtures/v4-core.cjs'),rows=fs.readFileSync(path.join(__dirname,'../recovery/original-v4-ledger.jsonl'),'utf8').trim().split('\n').map(JSON.parse),index=new Map(rows.map(r=>[r.id,r]));let w=V4.clone(rows[0].world),n=0;
 for(const r of rows.filter(r=>r.type==='commit')){const d=V4.clone(w),a=V4.byId(d,r.subject);for(const id of r.receipts){const q=index.get(id);assert.equal(q.status,'valid');if(q.request.questions.intent)a.intent={id:q.response.answers.intent.choice,label:V4.GOALS[q.response.answers.intent.choice],receipt:id,formedAtCompleted:a.completed};}const o=V4.available(d,a).find(o=>o.id===r.decisions.action),result=V4.rawAction(d,a,o,r.decisions);w=V4.commitDraft(w,d,r.subject,result,r.receipts);assert.deepEqual(w.lastCommit.changes,r.changes);n++;}
 assert.equal(n,74);const supplied=JSON.parse(fs.readFileSync(path.join(__dirname,'../recovery/turn-74.snapshot.json'),'utf8'));assert.deepEqual(supplied.world,w);assert.equal(supplied.attempts,100);assert.ok(w.entities.every(a=>!Object.keys(a.known).length));
});
test('reported counts match the full user ledger, not a sample',()=>{const rows=fs.readFileSync(path.join(__dirname,'../recovery/original-v4-ledger.jsonl'),'utf8').trim().split('\n').map(JSON.parse);const counts={};rows.filter(r=>r.type==='commit').forEach(r=>counts[r.decisions.action]=(counts[r.decisions.action]||0)+1);assert.deepEqual(counts,{gather_food:17,eat:40,drink:17});assert.equal(rows.filter(r=>r.type==='request'&&r.httpStatus===200).length,100);assert.equal(rows.filter(r=>r.type==='planner').length,0);});
test('body perception makes fullness direction and fulfilled intent explicit',()=>{const w=C.genesis(),a=w.entities[0];a.body.satiety=96;a.body.hydration=95;a.intent={id:'nourish',formedAtCompleted:0};const p=C.perception(w,a);assert.match(p.body_semantics.scale,/NOT hungry/);assert.equal(p.body_semantics.food.state,'satisfied');assert.equal(p.body_semantics.food.headroom,4);assert.equal(p.intention_progress.complete,true);});
test('fullness feedback neither changes state nor bans a physically available action',()=>{const w=C.genesis(),a=w.entities[0];a.body.satiety=99;a.body.hydration=99;a.inventory.food=3;const before=C.fingerprint(w),r=C.actionRequest(w,a,'~typesafe/jev-latest');assert.equal(C.fingerprint(w),before);assert.ok(r.questions.action.criteria.eat);assert.ok(r.questions.action.criteria.drink);assert.match(r.questions.action.criteria.eat,/only 1.0 points/);});
test('satisfied nourishment is reconsidered before its three-action horizon expires',async()=>fixture(req=>answer(req,{intent:'manipulate',action:'gather_stone'}),async calls=>{const s=session(),a=s.world.entities[0];a.intent={id:'nourish',label:'Food',formedAtCompleted:0};a.completed=1;a.body.satiety=99;a.body.hydration=90;assert.equal(await s.step(),true);assert.ok(calls[0].questions.intent);assert.equal(s.world.entities[0].intent.id,'manipulate');}));
test('one ordinary meal records measurable evidence but grants no skill or inference',()=>{const w=C.genesis();w.entities[0].inventory.food=3;const x=act(w,'eat');assert.equal(x.world.entities[0].foodEvidence.length,1);assert.equal(x.result.learning.length,0);assert.deepEqual(x.world.entities[0].known,{});assert.equal(x.world.entities[0].foodEvidence[0].gain,21);});
test('a second ordinary meal produces a candidate, not an automatically unlocked skill',()=>{const w=C.genesis();w.entities[0].inventory.food=3;const one=act(w,'eat');const two=act(one.world,'eat');assert.equal(two.result.learning.length,1);assert.equal(two.result.learning[0].skill,'foraging');assert.match(two.result.learning[0].feedback,/personal fruit-eating episodes/);assert.deepEqual(two.world.entities[0].known,{});});
test('a saturated meal with no gain cannot fabricate food evidence',()=>{const w=C.genesis(),a=w.entities[0];a.body.satiety=100;a.inventory.food=1;const x=act(w,'eat');assert.equal(x.result.learning.length,0);assert.equal(x.world.entities[0].foodEvidence?.length||0,0);assert.ok(x.world.entities[0].behavior.lastOutcome.low_information);});
test('ordinary food recognition requires a real inference phase in the session pipeline',async()=>fixture(req=>answer(req,{action:'eat',inference:'supported'}),async calls=>{const s=session({hierarchical:false});const a=s.world.entities[0];a.inventory.food=2;a.foodEvidence=[{event:'Tprevious',turn:0,before:45,after:66,gain:21}];assert.equal(await s.step(),true);assert.equal(calls.length,2);assert.ok(calls[1].questions.inference);const learned=s.world.entities[0].known.foraging;assert.ok(learned.receipt);assert.equal(s.world.lastCommit.receipts.length,2);assert.deepEqual(s.world.entities[1].known,{});}));
test('an uncertain inference preserves evidence without granting knowledge',async()=>fixture(req=>answer(req,{action:'eat',inference:'uncertain'}),async()=>{const s=session({hierarchical:false}),a=s.world.entities[0];a.inventory.food=2;a.foodEvidence=[{event:'Tprevious',turn:0,before:45,after:66,gain:21}];assert.equal(await s.step(),true);assert.deepEqual(s.world.entities[0].known,{});assert.equal(s.world.entities[0].foodEvidence.length,2);}));
test('failed required inference rolls back the meal, evidence and the whole turn',async()=>fixture((req,n)=>n===1?answer(req,{action:'eat'}):{model:'typesafe/jev-test-fixture',answers:{}},async()=>{const s=session({hierarchical:false}),a=s.world.entities[0];a.inventory.food=2;a.foodEvidence=[{event:'Tprevious',turn:0,before:45,after:66,gain:21}];const before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(C.fingerprint(s.world),before);assert.ok(s.log.some(r=>r.type==='request'&&r.status==='valid'&&!r.committed));}));
test('food and water effects log actual clamped gains rather than nominal gains',()=>{let w=C.genesis();w.entities[0].body.satiety=96;w.entities[0].inventory.food=1;let x=act(w,'eat');assert.equal(x.world.entities[0].behavior.lastOutcome.actual_body_gains.satiety,4);assert.match(x.result.notices[0].text,/actual gain 4/);w=C.genesis();w.entities[0].body.hydration=97;x=act(w,'drink');assert.equal(x.world.entities[0].behavior.lastOutcome.actual_body_gains.hydration,3);assert.equal(x.world.entities[0].behavior.stagnant,1);});
test('alternating low-benefit actions are detected even without a three-action streak',()=>{const a=C.genesis().entities[0];a.behavior={stagnant:0,history:[true,true,false,true,true,false].map((low,i)=>({action:i%2?'drink':'eat',low_information:low,learned:false}))};const r=C.stagnationReport(a);assert.equal(r.stalled,true);assert.equal(r.lowBenefitInWindow,4);});
test('useful repeated survival actions do not trigger a diversity quota',()=>{const a=C.genesis().entities[0];a.behavior={stagnant:0,history:Array.from({length:6},()=>({action:'eat',low_information:false,learned:false}))};assert.equal(C.stagnationReport(a).stalled,false);});
test('an adopted new belief interrupts the low-benefit cycle guard',()=>{const a=C.genesis().entities[0];a.behavior={stagnant:0,history:Array.from({length:6},(_,i)=>({action:'eat',low_information:i<5,learned:i===5}))};assert.equal(C.stagnationReport(a).stalled,false);});
test('an exhausted budget never sends an HTTP request, never resets the count',async()=>fixture(()=>{throw Error('NO NETWORK EXPECTED');},async calls=>{const s=session({cap:100});s.attempts=100;const before=C.fingerprint(s.world);assert.equal(await s.step(),false);assert.equal(s.status,'limited');assert.equal(s.attempts,100);assert.equal(calls.length,0);assert.equal(C.fingerprint(s.world),before);await s.step();assert.equal(s.log.filter(r=>r.type==='budget_stop').length,1);}));
test('minimum phase budget is checked before spending on a new intention',async()=>fixture(()=>{throw Error('NO NETWORK EXPECTED');},async calls=>{const s=session({cap:1});assert.equal(await s.step(),false);assert.equal(s.status,'limited');assert.equal(s.attempts,0);assert.equal(calls.length,0);assert.equal(s.log.at(-1).required,2);}));
test('limit changes require explicit validation and never start calls or lose credentials',async()=>fixture(()=>{throw Error('NO NETWORK EXPECTED');},async calls=>{const s=session({cap:100});s.attempts=100;s.updateLimits(200);assert.equal(s.config.cap,200);assert.equal(s.attempts,100);assert.equal(s.connected,true);assert.equal(s.running,false);assert.equal(s.status,'paused');assert.equal(calls.length,0);assert.throws(()=>s.updateLimits(100));assert.throws(()=>s.updateLimits(Infinity));assert.throws(()=>s.updateLimits(5000));}));
test('restoration preserves the spent count but never raises the spending cap',()=>{const saved=JSON.parse(fs.readFileSync(path.join(__dirname,'../recovery/turn-74.snapshot.json'),'utf8'));const s=new Session();s.restore(saved);assert.equal(s.world.tick,74);assert.equal(s.attempts,100);assert.equal(s.config.cap,100);assert.equal(s.connected,false);assert.equal(s.running,false);assert.ok(s.world.entities.every(a=>!a.foodEvidence&&!Object.keys(a.known).length));});
test('connection logs include actual mode and planner configuration',()=>{const s=session();const row=s.log.find(r=>r.type==='connection');assert.equal(row.planner,'none');assert.equal(row.transport,'direct');assert.equal(row.engineVersion,C.VERSION);assert.ok(!JSON.stringify(s.export()).includes('TEST_CREDENTIAL_ONLY'));});

test('invalid imported food evidence and outcome-history shapes are rejected',()=>{let w=C.genesis();w.entities[0].foodEvidence='not an array';assert.throws(()=>C.validateWorld(w),/food evidence/);w=C.genesis();w.entities[0].behavior.history='not an array';assert.throws(()=>C.validateWorld(w),/outcome history/);});
test('supplied-session recovery route requires a local token and sends no model request',async()=>{const {createServer}=require('../server.cjs');let upstream=0;const dataDir=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'origin-v41-'));const server=createServer({env:{},dataDir,recoveryPath:path.join(__dirname,'../recovery/turn-74.snapshot.json'),fetchImpl:async()=>{upstream++;throw Error('No upstream expected');}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const base='http://127.0.0.1:'+server.address().port;assert.equal((await fetch(base+'/api/recovery')).status,403);const bootstrap=await (await fetch(base+'/api/bootstrap')).json();assert.equal(bootstrap.suppliedRecovery,true);const res=await fetch(base+'/api/recovery',{headers:{'X-Origin-Token':bootstrap.token}});assert.equal(res.status,200);const recovered=await res.json();assert.equal(recovered.world.tick,74);assert.equal(recovered.attempts,100);assert.equal(upstream,0);}finally{await new Promise(resolve=>server.close(resolve));fs.rmSync(dataDir,{recursive:true,force:true});}});
