'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {WorldService}=require('../source/world-service.cjs'),L=require('../source/civilization.js');
const KEY='TEST-ONLY-NOT-A-REAL-SECRET';
function answer(req){const pick={action:'rest',expression:'neutral',intent:'recover',domain:'body',inference:'uncertain',response:'decline'};return {model:'jev-TEST-FIXTURE',answers:Object.fromEntries(Object.entries(req.questions).map(([k,q])=>{const choice=pick[k] in q.criteria?pick[k]:Object.keys(q.criteria)[0];return [k,{type:'choice',choice,confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(v=>[v,v===choice?1:0]))}];})),usage:{input_tokens:1,cost:0}};}
async function make(t,options={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'origin6-test-'));let calls=0;const env={TYPESAFE_API_KEY:KEY,...options.env};const service=new WorldService({dataDir:dir,env,fixture:true,fetchImpl:async(url,init)=>{calls++;if(options.response)return options.response(url,init);return Response.json(answer(JSON.parse(init.body)));}});await service.ready;t.after(async()=>{await service.settle();await service.close();await fs.rm(dir,{recursive:true,force:true});});return {service,dir,get calls(){return calls;}};}
const wait=async test=>{const until=Date.now()+3000;while(!test()&&Date.now()<until)await new Promise(r=>setTimeout(r,10));assert.ok(test(),'Timed out waiting for explicit condition');};
test('server startup and state reads cannot cause any inference or world time',async t=>{const x=await make(t);assert.equal(x.calls,0);const a=x.service.state();assert.equal(a.authoritative,true);assert.equal(a.world.simTime,0);assert.equal(a.connected,false);assert.equal(x.calls,0);});
test('authenticated connection config does not by itself authorize a call',async t=>{const x=await make(t);await x.service.command({action:'connect',config:{cap:50}});assert.equal(x.calls,0);assert.equal(x.service.session.running,false);assert.equal(x.service.session.connected,true);});
test('server lives start in parallel and preserve provider receipts',async t=>{const x=await make(t);await x.service.command({action:'connect',config:{cap:50}});await x.service.command({action:'start',oneWave:true,maxMinutes:80,allowDetached:true});await wait(()=>Object.keys(x.service.session.world.activities).length===6);const acts=Object.values(x.service.session.world.activities);assert.equal(new Set(acts.map(a=>a.start)).size,1);assert.ok(acts.every(a=>a.receipts.length>=2));assert.ok(x.service.session.log.filter(r=>r.type==='request').every(r=>r.testFixture));});
test('run authorization is a hard simulated-time limit rather than an unchecked timer',async t=>{const x=await make(t);await x.service.command({action:'connect',config:{cap:100,rate:120}});await x.service.command({action:'start',oneWave:true,maxMinutes:1,allowDetached:true});await wait(()=>Object.keys(x.service.session.world.activities).length===6);x.service.session.pump(2);assert.equal(x.service.session.world.simTime,1);assert.equal(x.service.session.running,false);assert.equal(x.service.session.state,'budget');});
test('an unaffordable cohort never dispatches upstream',async t=>{const x=await make(t);await x.service.command({action:'connect',config:{cap:5}});await x.service.command({action:'start',maxMinutes:60});await wait(()=>!x.service.session.busy);assert.equal(x.calls,0);assert.equal(x.service.session.world.simTime,0);assert.equal(x.service.session.state,'budget');});
test('provider rejection is logged with its HTTP status, never replaced by a local decision',async t=>{const x=await make(t,{response:()=>Response.json({detail:'TEST forbidden'},{status:401})});await x.service.command({action:'connect',config:{cap:30}});await x.service.command({action:'start',maxMinutes:60});await wait(()=>!x.service.session.busy);assert.equal(x.service.session.state,'error');assert.equal(Object.keys(x.service.session.world.activities).length,0);assert.ok(x.service.session.log.some(r=>r.httpStatus===401));assert.equal(x.service.session.world.simTime,0);});
test('checkpoint excludes all secrets and reopens paused with activities and budget intact',async t=>{const x=await make(t);await x.service.command({action:'connect',key:KEY,config:{cap:80}});await x.service.command({action:'start',oneWave:true,maxMinutes:200,allowDetached:true});await wait(()=>Object.keys(x.service.session.world.activities).length===6);await x.service.settle();x.service.session.world.entities[0].memory.push({text:KEY,event:'TEST-SECRET'});await x.service.save();const text=await fs.readFile(path.join(x.dir,'world-v6.json'),'utf8');assert.ok(!text.includes(KEY));const s2=new WorldService({dataDir:x.dir,env:{},fixture:true,fetchImpl:()=>{throw Error('No network on restart');}});await s2.ready;assert.equal(s2.session.running,false);assert.equal(s2.session.connected,false);assert.equal(Object.keys(s2.session.world.activities).length,6);assert.equal(s2.session.attempts,x.service.session.attempts);await s2.close();});
test('new scenario retains prior usage and records seeded setup',async t=>{const x=await make(t);x.service.session.attempts=74;await x.service.command({action:'scenario',scenario:'modern'});assert.equal(x.service.session.attempts,74);assert.ok(x.service.session.world.objects.length>25);assert.equal(x.service.session.running,false);assert.ok(x.service.session.world.chronicle.some(e=>e.kind==='scenario'));});
test('server edits are explicit commands and do not silently run lives',async t=>{const x=await make(t);await x.service.command({action:'appearance',subject:'S01',values:{name:'TEST Ada'}});assert.equal(x.service.session.world.entities[0].observerName,'TEST Ada');assert.equal(x.calls,0);await x.service.command({action:'room',room:{x:-5,z:-16,width:6,depth:6}});assert.equal(x.service.session.world.rooms[0].built,false);assert.equal(x.calls,0);});
test('v5-style save and retained reservations survive server round trip',async t=>{const x=await make(t);await x.service.command({action:'connect',config:{cap:50}});await x.service.command({action:'start',oneWave:true,maxMinutes:200});await wait(()=>Object.keys(x.service.session.world.activities).length===6);await x.service.settle();const snapshot=x.service.session.export(),time=snapshot.world.simTime;await x.service.command({action:'restore',snapshot});assert.equal(x.service.session.world.simTime,time);assert.equal(x.service.session.running,false);assert.equal(Object.keys(x.service.session.world.activities).length,6);});
test('read views share one authoritative world rather than duplicating simulations',async t=>{const x=await make(t);const a=x.service.state(),b=x.service.state();assert.equal(a.identity,b.identity);await x.service.command({action:'appearance',subject:'S01',values:{name:'Shared view'}});assert.equal(x.service.state().world.entities[0].observerName,'Shared view');assert.equal(x.calls,0);});
test('invalid terrain import leaves world and time unchanged',async t=>{const x=await make(t),terrain=JSON.stringify(x.service.session.world.terrain);await assert.rejects(x.service.command({action:'geography',anchor:{lat:45,lon:-73},dem:{values:[],metresPerUnit:20}}),/1089/);assert.equal(JSON.stringify(x.service.session.world.terrain),terrain);assert.equal(x.calls,0);});
module.exports={answer};
