(function(){'use strict';const L=window.OriginLife,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let category='All',roomCorner=null,drawRoom=false,roomHouse='H1',rotation=0,sound=false,lastConversation=null;
const quantity=o=>Object.entries(o||{}).filter(([,n])=>n>0).map(([k,n])=>'<span class="resource-chip">'+esc(L.items[k]?.label||k)+' <b>'+Number(n).toFixed(Number.isInteger(n)?0:1)+'</b></span>').join('')||'<span class="small">Empty</span>';
const button=(text,attr='')=>'<button class="compact" '+attr+'>'+text+'</button>';
function app(){return window.ORIGIN;}
async function command(action,data){const a=app();if(a.session.isRemote)return a.session.command(action,data);const w=a.session.world;let result;
 if(action==='room')result=L.draftRoom(w,data.room);else if(action==='appearance')result=L.appearance(w,data.subject,data.values);else if(action==='scenario'){a.session.reset(data.scenario);return;}else if(action==='geography')result=L.relocate(w,data.anchor,data.dem);else if(action==='lifeScale'){w.settings.yearDays=data.yearDays;w.settings.gestationDays=data.gestationDays;}else throw Error('This operation requires the local server.');a.session.publish();return result;
}
function card(title,body){return '<article class="civic-card"><h3>'+title+'</h3>'+body+'</article>';}
function render(page,ctx){const {session,selected}=ctx,w=session.world,a=L.byId(w,selected),out=$('overlay');let h='';
 if(page==='audit'){
  const rows=L.agency.audit(w);
  h='<div class="micro gold">CAUSAL FEEDBACK / NO INFERENCE ON THIS SCREEN</div><h2>Are their lives progressing?</h2><p>This view reads completed events, body reserves and interruptions. A warning never selects a replacement action, grants knowledge or invents a success.</p><p class="civic-notice">'+session.attempts+' Jev requests attempted / '+session.plannerAttempts+' planner requests. '+w.tick+' initiated activities completed. Shared time: '+Math.round(w.simTime)+' minutes. Imported receipts remain unverified historical records.</p><div class="civic-grid">';
  for(const r of rows){const reasons=[...(r.reason?[r.reason]:[]),...r.historical];
   h+=card(esc(r.name)+' <span class="micro quiet">'+r.id+'</span>','<p><b>'+esc(r.activity)+'</b></p><p>'+ (r.needs.urgent.length?'Low reserves: '+esc(r.needs.urgent.join(', ')):'No severely depleted body reserve detected.')+'</p><p>Intention: '+esc(r.intent.id||'not yet chosen')+' / '+esc(r.intent.reason)+'</p><p>Status: <b>'+(r.paused?'PAUSED FOR REVIEW':r.reviewDue?'JEV RECONSIDERATION DUE':'MONITORED')+'</b></p>'+reasons.map(t=>'<p class="civic-notice">'+esc(t)+'</p>').join('')+'<p>'+r.interruptions.length+' interruptions in the last 120 simulated minutes.</p><div>'+r.recent.map(e=>'<p class="small"><b>'+esc(e.kind)+' / '+esc(e.role)+'</b><br>'+esc(e.result)+'<br>Evidence '+esc(e.event)+(e.low?' / LOW BENEFIT':'')+'</p>').join('')+'</div>');
  }h+='</div><p class="small">Review does not refill needs, reset history or raise budgets. It authorizes another model evaluation. A renewed sequence of ineffective outcomes pauses spending again.</p>';
 }else if(page==='build'){
  const cats=['All','Sleep','Comfort','Food','Hygiene','Family','Production','Knowledge','Utilities','Art and play','Exchange'];
  h='<div class="micro gold">DESIGN / MATERIALS / WORK / A PLACE TO LIVE</div><h2>Make somewhere belong.</h2><p>Plans are proposals. No building or furniture appears until an individual chooses and completes the work with materials.</p><div class="civic-toolbar">'+cats.map(c=>button(esc(c),'data-catalog="'+esc(c)+'" class="compact '+(category===c?'chosen':'')+'"')).join('')+'</div>';
  h+=card('Design a room','<form id="room-form" class="room-form"><label>NAME<input id="room-name" value="A shared home" maxlength="60"></label><div class="four"><label>X<input id="room-x" type="number" value="-12" min="-38" max="38"></label><label>Z<input id="room-z" type="number" value="-12" min="-38" max="38"></label><label>WIDTH<input id="room-w" type="number" value="8" min="4" max="14"></label><label>DEPTH<input id="room-d" type="number" value="8" min="4" max="14"></label></div><div class="two"><label>DOOR<select id="room-door"><option value="south">South</option><option value="north">North</option><option value="east">East</option><option value="west">West</option></select></label><label>HOUSEHOLD<select id="room-home">'+w.households.map(h=>'<option value="'+h.id+'">'+esc(h.name)+'</option>').join('')+'</select></label></div><div class="row"><button class="primary">Propose room</button><button type="button" id="draw-room">Draw two corners in world</button></div><p class="small">Four construction phases. Each phase consumes wood, fibre and stone. Doorways affect navigation; completed roofs provide shelter.</p></form>');
  h+='<div class="civic-toolbar"><label>FURNITURE ROTATION <select id="furniture-rotation">'+[0,90,180,270].map(n=>'<option value="'+n+'" '+(rotation===n?'selected':'')+'>'+n+'&deg;</option>').join('')+'</select></label></div><div class="catalog-grid">';
  for(const [id,o]of Object.entries(L.OBJECTS)){const meta=L.furniture[id],cat=meta?.category||'Production';if(category!=='All'&&cat!==category)continue;const cost=L.objectCost(id),known=!o.skill||a.known[o.skill];h+='<article class="furniture-card"><div class="object-glyph glyph-'+(meta?.use||'craft')+'">'+esc(o.label[0])+'</div><span class="micro quiet">'+esc(cat)+'</span><h3>'+esc(o.label)+'</h3><div class="small">'+quantity(cost)+'</div><p class="small">'+(known?'Technique available to selected person':'Needs '+esc(L.RECIPES[o.skill]?.name||o.skill))+(meta?.power?' / requires power':'')+(meta?.water?' / consumes water':'')+'</p>'+button('Place proposal','data-blueprint="'+id+'"')+'</article>';}
  h+='</div><h3>Plans and constructed rooms</h3>'+w.rooms.map(r=>card(esc(r.name||r.id),'<p>'+r.width+' &times; '+r.depth+' / '+r.household+' / '+(r.built?'Habitable':'Phase '+r.progress+'/'+r.phases)+'</p><div class="progress"><i style="width:'+100*r.progress/r.phases+'%"></i></div><p class="small">Per phase: '+quantity(r.material)+'</p>')).join('');
 }else if(page==='world'){
  h='<div class="micro gold">EARTH ATLAS / LOCAL ENVIRONMENT</div><h2>A place on Earth.</h2><canvas id="earth-map" width="1000" height="500" aria-label="Natural Earth world land map; click to choose coordinates"></canvas><p class="small">Land outlines: Natural Earth, public domain. No political borders. Click to choose an anchor. This is a world atlas, not a claim that every region is being simulated.</p><form id="earth-form"><div class="two"><label>LATITUDE<input id="earth-lat" type="number" step="0.0001" min="-80" max="80" value="'+w.terrain.anchor.lat+'"></label><label>LONGITUDE<input id="earth-lon" type="number" step="0.0001" min="-180" max="180" value="'+w.terrain.anchor.lon+'"></label></div><div class="row"><button class="primary" type="button" id="load-dem">Load real elevation (online)</button><button type="submit">Use generated local terrain</button><button type="button" id="import-dem">Import an elevation file</button></div></form><p class="civic-notice">'+esc(w.terrain.provenance)+'</p><p class="small">Terrain import requires no active activities. Real elevation is a sampled terrain tile. Plants, watercourses and mineral stocks remain generated game estimates, not surveyed Earth resources.</p>';
  h+='<div class="civic-grid">'+card('Season and weather','<div class="metric">'+esc(w.climate.season)+' / '+w.climate.temperature+'&deg;</div><p>'+esc(w.weather)+' / wind '+w.climate.wind+'</p><small>Modeled climate, not a live weather service.</small>')+card('Local ecology','<div class="metric">'+Math.floor(w.ecology.regrown)+' regrown units</div><p>Extracted: '+w.ecology.harvested+' / water used: '+w.ecology.waterUsed+'</p><p>Stored food spoils. Mineral deposits do not regenerate.</p>')+'</div><h3>Resources have locations</h3><div class="resource-table">'+w.nodes.map(n=>'<div class="list-row"><b>'+esc(n.kind)+'</b><span>'+n.quantity+' available / '+n.reserved+' reserved</span><small>'+n.id+'</small></div>').join('')+'</div>';
 }else if(page==='households'){
  h='<div class="micro gold">GENERATIONS / PRIVATE SPACES / SHARED RESPONSIBILITIES</div><h2>More than a population.</h2><div class="civic-grid">'+w.households.map(h=>card(esc(h.name),'<div class="family-members">'+h.members.map(id=>{const p=L.byId(w,id);return p?button(esc(p.observerName)+' / '+p.stage,'data-person="'+id+'"'):'';}).join(' ')+'</div><p>'+quantity({food:h.food,...h.stores})+'</p><p class="small">'+w.rooms.filter(r=>r.household===h.id&&r.built).length+' habitable rooms / '+w.objects.filter(o=>o.household===h.id).length+' objects</p>')).join('')+'</div><h3>Family connections</h3><div class="family-tree">'+w.entities.map(p=>'<article class="family-node"><button data-person="'+p.id+'">'+esc(p.observerName)+'</button><small>'+p.stage+' / '+Math.floor(p.ageYears)+' years</small><p>Parents: '+(p.parents.join(' + ')||'Founding generation')+'<br>Partner: '+(p.partner||'None')+'<br>Children: '+(p.children.join(', ')||'None')+'</p>'+(p.pregnancy?'<p class="gold">Pregnancy / '+Math.ceil((p.pregnancy.due-w.simTime)/1440)+' days</p>':'')+'</article>').join('')+'</div><p class="small">Only consenting adults can form romantic partnerships or start the abstract family action. Practical knowledge is never inherited. Personal lessons and practice are tracked separately.</p>';
 }else if(page==='economy'){
  const escrow=w.contracts.reduce((s,j)=>s+j.escrow,0),coins=w.entities.reduce((s,a)=>s+(a.inventory.coin||0),0)+w.households.reduce((s,h)=>s+(h.stores.coin||0),0);
  h='<div class="micro gold">WORK / BARTER / FINITE GOODS</div><h2>An economy made of actions.</h2><div class="civic-grid">'+card('Exchange tokens','<div class="metric">'+coins+'</div><p>Held by people and households. '+escrow+' tokens locked in funded contracts.</p>')+card('Real transfers','<div class="metric">'+w.society.barters+' barters</div><p>'+w.society.workDelivered+' deliveries completed. No income appears without a funded source.</p>')+'</div><h3>Funded contracts</h3>'+(w.contracts.length?w.contracts.slice(-30).map(j=>card(j.id+' / '+esc(j.state),'<p>'+j.quantity+' '+esc(j.resource)+' for '+j.reward+' tokens</p><small>Owner '+j.owner+' / worker '+(j.worker||j.claimant||'not chosen')+' / escrow '+j.escrow+'</small>')).join(''):'<p class="empty">No one has chosen to fund a contract yet. First Minds begins without exchange tokens; barter remains available.</p>')+'<h3>Exchange history</h3>'+w.trades.slice(-20).reverse().map(t=>'<div class="item">'+t.from+' &harr; '+t.to+'<p>'+quantity(t.give)+' for '+quantity(t.receive)+'</p><small>Receipts '+t.receipts.join(', ')+'</small></div>').join('');
 }else if(page==='civilization'){
  const skills=new Set(w.entities.flatMap(p=>Object.keys(p.known)));h='<div class="micro gold">MATERIAL CULTURE / INFRASTRUCTURE / KNOWLEDGE</div><h2>A civilization leaves evidence.</h2><div class="civic-grid">'+card('Power','<div class="metric">'+w.networks.energy.toFixed(2)+'</div><p>Stored game energy units. Generated '+w.networks.generated.toFixed(2)+' / consumed '+w.networks.consumed.toFixed(2)+'</p>')+card('Water','<div class="metric">'+w.networks.water+'</div><p>Stored finite units. Plumbing and hygiene use available water.</p>')+card('Knowledge in people','<div class="metric">'+skills.size+' / '+Object.keys(L.RECIPES).length+'</div><p>Known processes are personal. A record or lesson does not automatically grant practical competence.</p>')+card('Material memory','<div class="metric">'+w.artifacts.length+'</div><p>Written records, art and executable test results created through completed actions.</p>')+'</div><h3>Persistent works</h3>'+(w.artifacts.length?w.artifacts.slice(-30).reverse().map(b=>card(esc(b.title||b.type),'<p>'+esc(b.author)+' / '+esc(b.type)+'</p><small>Evidence '+esc(b.receipt)+(b.type==='program'?' / executed result '+esc(b.result):'')+'</small>')).join(''):'<p class="empty">No work has been created in this run.</p>')+'<p class="civic-notice">Technologies are a bounded, inspectable process catalog. An iron output, a truth-table check and a trained numeric predictor are different levels of evidence, not a guarantee of open-ended invention or consciousness.</p>';
 }else if(page==='creator'){
  h='<div class="micro gold">CREATE / IDENTITY / DECLARED OBSERVER EDIT</div><h2>One person, not a clone.</h2><p>Appearance, names and traits can be edited. These edits are logged as observer interventions, not as learned life events. Stop this person\'s activity before editing.</p><form id="creator-form"><label>PERSON<select id="creator-person">'+w.entities.map(p=>'<option value="'+p.id+'" '+(p.id===selected?'selected':'')+'>'+esc(p.observerName)+' / '+p.id+'</option>').join('')+'</select></label><label>NAME<input id="creator-name" maxlength="40" value="'+esc(a.observerName)+'"></label><div class="three"><label>SKIN<input id="creator-skin" type="color" value="'+a.skin+'"></label><label>HAIR<input id="creator-hair" type="color" value="'+a.hair+'"></label><label>CLOTHING<input id="creator-cloth" type="color" value="'+a.cloth+'"></label></div><label>TRAITS / UP TO THREE</label><div class="traits-grid">'+['curious','patient','sociable','playful','practical','independent','caring','quiet','creative','bold'].map(t=>'<label><input type="checkbox" name="creator-trait" value="'+t+'" '+(a.traits.includes(t)?'checked':'')+'> '+t+'</label>').join('')+'</div><button class="primary">Apply declared edit</button></form><h3>Personal project</h3>'+card(a.aspiration?esc(a.aspiration.label):'Not yet chosen',a.aspiration?'<p>'+a.aspiration.progress+' / '+a.aspiration.target+' completed relevant activities</p>':'<p>This individual must choose their own project through Jev.</p>')+'<h3>Active experiences</h3>'+a.moodlets.map(m=>'<div class="item">'+esc(m.label)+'<small>'+esc(m.source)+' / '+Math.ceil(m.until-w.simTime)+' minutes remaining</small></div>').join('');
 }else if(page==='conversations'){
  h='<div class="micro gold">HEARD / INTERPRETED / REMEMBERED</div><h2>No invisible conversation.</h2><p>Only messages and signals actually carried by an authorized interaction appear here. Generated dialogue requires a connected LLM planner and learned language.</p>'+w.conversations.slice(-40).reverse().map(c=>'<article class="conversation-card"><div class="micro gold">'+c.people.join(' &harr; ')+' / '+Math.floor(c.time)+' MIN</div><blockquote>'+esc(c.spoken||c.token||'Nonverbal '+c.kind.replaceAll('_',' '))+'</blockquote><small>'+esc(c.source)+'<br>'+c.receipts.join(', ')+'</small></article>').join('')+(!w.conversations.length?'<p class="empty">No conversation has completed yet. There are no prewritten chat transcripts.</p>':'');
 }else return false;
 out.innerHTML=h;out.hidden=false;setTimeout(()=>{if(page==='world')earth();},0);return true;
}
function earth(){const c=$('earth-map');if(!c)return;const g=c.getContext('2d'),land=window.ORIGIN_EARTH,gx=lon=>(lon+180)/360*c.width,gy=lat=>(90-lat)/180*c.height;g.fillStyle='#1d383b';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#a9c5af18';for(let x=0;x<=c.width;x+=c.width/12){g.beginPath();g.moveTo(x,0);g.lineTo(x,c.height);g.stroke();}for(let y=0;y<=c.height;y+=c.height/6){g.beginPath();g.moveTo(0,y);g.lineTo(c.width,y);g.stroke();}
 for(const f of land.features){const polygons=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];for(const poly of polygons){g.beginPath();for(const ring of poly){ring.forEach(([lon,lat],i)=>i?g.lineTo(gx(lon),gy(lat)):g.moveTo(gx(lon),gy(lat)));g.closePath();}g.fillStyle='#80967a';g.fill('evenodd');}}
 const w=app().session.world,p=w.terrain.anchor;g.fillStyle='#edd49b';g.beginPath();g.arc(gx(p.lon),gy(p.lat),5,0,7);g.fill();g.font='16px Arial';g.fillText('ACTIVE SETTLEMENT',gx(p.lon)+10,gy(p.lat)-10);c.onclick=e=>{const b=c.getBoundingClientRect(),lon=(e.clientX-b.left)/b.width*360-180,lat=90-(e.clientY-b.top)/b.height*180;$('earth-lat').value=Math.max(-80,Math.min(80,lat)).toFixed(4);$('earth-lon').value=lon.toFixed(4);};
}
function ground(p){if(!drawRoom)return false;const ui=app().ui;if(!roomCorner){roomCorner={x:Math.round(p.x),z:Math.round(p.z)};ui.toast('First corner selected. Click the opposite corner.');}else{const x=(roomCorner.x+Math.round(p.x))/2,z=(roomCorner.z+Math.round(p.z))/2,width=Math.abs(roomCorner.x-Math.round(p.x)),depth=Math.abs(roomCorner.z-Math.round(p.z));drawRoom=false;roomCorner=null;ui.guarded(async()=>{await command('room',{room:{x,z,width,depth,household:roomHouse,name:'Drawn room',door:'south'}});ui.toast('Room proposed. Four material work phases are required.');});}return true;}
function afterDraw(){const a=app();if(!a)return;const w=a.session.world;const p=$('civil-pulse');if(p)p.innerHTML='<b>'+esc(w.climate?.season||'')+'</b> '+(w.climate?.temperature??'')+'&deg; <span>'+w.rooms.filter(r=>r.built).length+' rooms</span> <span>'+w.nodes.length+' resource sites</span> <span>'+w.artifacts.length+' works</span>';
 if($('render-status')&&a.view)$('render-status').textContent=a.view.rendererName||'THREE.JS / LIVE WORLD STATE';
 if(sound&&w.conversations.length){const c=w.conversations.at(-1);if(c.id!==lastConversation&&c.spoken){lastConversation=c.id;const u=new SpeechSynthesisUtterance(c.spoken);u.lang='en-US';u.rate=.94;speechSynthesis.speak(u);}}
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=app();if(!a)return;const ui=a.ui;
 if(b.dataset.catalog){category=b.dataset.catalog;ui.refresh();}
 if(b.id==='draw-room'){drawRoom=true;roomCorner=null;roomHouse=$('room-home').value;ui.page('live');ui.toast('Click two opposite corners, 4 to 14 units apart. Escape cancels.');}
 if(b.dataset.scenario)ui.guarded(async()=>{if(confirm('Replace the current world? Initial structures and skills in this scenario are openly seeded. Save first.'))await command('scenario',{scenario:b.dataset.scenario});});
 if(b.id==='create-person-btn')ui.page('creator');
 if(b.id==='three-btn')ui.guarded(async()=>{ui.toast('Loading the Three.js renderer. The isometric world remains available if loading fails.');await a.view.enableThree();});
 if(b.id==='iso-btn'){a.view.disableThree();ui.toast('Isometric view shows the same authoritative world.');}
 if(b.id==='voice-btn'){sound=!sound;b.textContent=sound?'Voice on':'Voice off';if(!sound)speechSynthesis.cancel();ui.toast(sound?'Browser voice reads only completed LLM dialogue; it does not invent speech.':'Voice disabled.');}
 if(b.id==='load-dem')ui.guarded(async()=>{if(!a.session.isRemote)throw Error('Start the included server to import public elevation.');const lat=Number($('earth-lat').value),lon=Number($('earth-lon').value);ui.toast('Fetching a public elevation tile. No LLM call is used.');const data=await a.session.api('/api/world/terrain',{method:'POST',body:JSON.stringify({lat,lon})});await command('geography',{anchor:{lat,lon},dem:data.dem});ui.toast('Actual elevation imported. Generated ecology and minerals remain labeled separately.');ui.refresh();});
 if(b.id==='import-dem')$('terrain-file').click();
});
document.addEventListener('change',e=>{if(e.target.id==='furniture-rotation')rotation=Number(e.target.value);if(e.target.id==='creator-person'){app().ui.choose(e.target.value);app().ui.refresh();}});
document.addEventListener('submit',e=>{const id=e.target.id,a=app();if(!a)return;const ui=a.ui;
 if(id==='room-form'){e.preventDefault();ui.guarded(async()=>{await command('room',{room:{name:$('room-name').value,x:Number($('room-x').value),z:Number($('room-z').value),width:Number($('room-w').value),depth:Number($('room-d').value),door:$('room-door').value,household:$('room-home').value}});ui.toast('Room blueprint added; no materials were created.');ui.refresh();});}
 if(id==='creator-form'){e.preventDefault();ui.guarded(async()=>{await command('appearance',{subject:$('creator-person').value,values:{name:$('creator-name').value,skin:$('creator-skin').value,hair:$('creator-hair').value,cloth:$('creator-cloth').value,traits:[...document.querySelectorAll('[name=creator-trait]:checked')].map(n=>n.value)}});await a.view?.refreshPeople?.();ui.toast('Declared edit saved.');ui.refresh();});}
 if(id==='earth-form'){e.preventDefault();ui.guarded(async()=>{await command('geography',{anchor:{lat:Number($('earth-lat').value),lon:Number($('earth-lon').value)}});ui.toast('Anchor selected; generated local terrain explicitly labeled.');ui.refresh();});}
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){drawRoom=false;roomCorner=null;}});
setTimeout(()=>{if($('terrain-file'))$('terrain-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;await app().ui.guarded(async()=>{if(file.size>2e6)throw Error('Elevation file exceeds 2 MB.');const dem=JSON.parse(await file.text());await command('geography',{anchor:dem.anchor||app().session.world.terrain.anchor,dem});app().ui.toast('Elevation grid imported with its provenance.');});e.target.value='';};},0);
window.OriginPanels={render,ground,afterDraw,get rotation(){return rotation;}};
})();
