(function(){'use strict';const L=window.OriginLife,P=window.OriginProviders,$=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view=null,selected='S01',page='live',tab='story',modal=null,lastDraw=0,lastOverlay=0,buildType=null;
const session=new (location.protocol==='file:'?window.LivingSession:window.RemoteSession)({change:()=>schedule(),frame:w=>{if(view?.ready)view.sync(w);schedule();},reset:w=>{selected=w.entities[0].id;initView(w);schedule();},canRun:()=>!!view?.ready});
window.ORIGIN={session,get view(){return view;},get selected(){return selected;},ui:{toast,guarded,page:value=>{page=value;drawPage();},refresh:()=>{draw();drawPage();},choose}};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,7000);}
function show(id){for(const n of document.querySelectorAll('.modal-backdrop'))n.hidden=true;modal=id;$(id).hidden=false;setTimeout(()=>$(id).querySelector('input,button,select,textarea')?.focus(),0);if(id==='ledger-modal'){drawLedger();if(session.isRemote)guarded(async()=>{await session.fullLedger();drawLedger();});}if(id==='budget-modal')budgetFields();if(id==='connect-modal')connectionFields();}
function close(){for(const n of document.querySelectorAll('.modal-backdrop'))n.hidden=true;modal=null;}
function download(name,value,type='application/json'){const b=value instanceof Blob?value:new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function guarded(fn){try{return await fn();}catch(e){toast(e.message);return null;}}
async function initView(w){if(view){view.dispose?.();view.ready=false;$('world').replaceChildren();$('labels').replaceChildren();}view=new window.CivilizationView($('world'),$('labels'),choose);view.onObject=id=>{page='build';drawPage();toast('Selected '+id);};view.onGround=p=>{if(window.OriginPanels?.ground(p))return;if(!buildType)return;guarded(async()=>{const type=buildType;buildType=null;if(session.isRemote)await session.command('blueprint',{type,x:Math.round(p.x),z:Math.round(p.z),rotation:window.OriginPanels.rotation});else{L.blueprint(session.world,type,Math.round(p.x),Math.round(p.z));session.publish();}toast('Blueprint proposed. A person must choose to build it with materials.');drawPage();});};
 $('loading').hidden=false;$('load-text').textContent='Preparing the shared world. Loading the view makes no AI request.';$('retry-render').hidden=true;
 try{await view.init(w);$('loading').hidden=true;$('render-status').textContent=view.rendererName;}
 catch(e){$('load-text').textContent=e.message;$('retry-render').hidden=false;$('loading-help').hidden=false;$('render-status').textContent='VIEW UNAVAILABLE';}
}
function choose(id){if(!L.byId(session.world,id))return;selected=id;view?.select(id);if(innerWidth<=760&&page==='live')$('right').classList.add('open');draw();}
function schedule(){if(!schedule.pending){schedule.pending=true;requestAnimationFrame(()=>{schedule.pending=false;if(performance.now()-lastDraw>120){draw();lastDraw=performance.now();}});}}
function humanName(id){const a=L.byId(session.world,id);return a?escape(a.observerName)+' <span class="quiet">'+escape(id)+'</span>':escape(id);}
const meters={satiety:'Fullness',hydration:'Hydration',energy:'Energy',warmth:'Warmth',health:'Health',hygiene:'Hygiene',bladder:'Bladder comfort',social:'Social connection',fun:'Enjoyment',comfort:'Comfort'};
function draw(){const s=session,w=s.world,a=L.byId(w,selected)||w.entities[0];selected=a.id;const t=Math.floor(w.minutes%1440);$('clock').textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');$('day').textContent='DAY '+String(Math.floor(w.minutes/1440)+1).padStart(2,'0')+' / '+w.weather.toUpperCase();
 $('population-count').textContent=w.entities.filter(p=>p.alive).length;$('active-count').textContent=Object.keys(w.activities).length;$('calls').textContent=s.attempts+' / '+s.config.cap;$('mode-badge').textContent=s.connected?(s.config.planner==='none'?'JEV / PARALLEL LIVES':'HYBRID / JEV DECISIONS'):'JEV REQUIRED';
 $('status-title').textContent=({locked:'The world is waiting.',running:'Lives in parallel.',planning:'Independent minds are deciding.',budget:({planner:'Planner budget reached.',jev:'Jev budget reached.',time:'Approved run window reached.'})[s.budgetStop?.kind]||'Request budget reached.',review:'A life needs review.',error:'Provider request stopped.',paused:'World paused.',ready:'Ready for real decisions.'})[s.state]||s.state;$('status-text').textContent=s.error||s.phase;$('run-btn').textContent=s.running?'Pause':'Run lives';$('wave-btn').disabled=s.busy||s.running;
 $('roster').innerHTML=w.entities.map(p=>{const ac=w.activities[p.activity];return '<button class="resident '+(p.id===selected?'active':'')+'" data-person="'+p.id+'"><span class="portrait" style="background:'+p.cloth+'">'+p.id.slice(1)+'</span><span><b>'+escape(p.observerName)+'</b><small>'+escape(!p.alive?'Deceased':ac?.label||(p.cognition.pending?'Awaiting Jev':p.cognition.stalled?'Needs review':'Awaiting decision'))+'</small></span>'+(ac?'<span class="green-dot"></span>':'')+'</button>';}).join('');
 $('roster-bottom').textContent=Object.keys(w.activities).length+' active / '+w.entities.filter(p=>p.cognition.pending).length+' awaiting AI';$('person-name').textContent=a.observerName;$('person-meta').textContent=a.id+' / '+Math.floor(a.ageYears)+' years / '+a.stage+' / '+a.household+'\n'+a.traits.join(' + ');$('mood').textContent=a.mood?.label||'Unexpressed';
 $('needs').innerHTML=L.NEEDS.map(k=>'<div><div class="need-row"><span>'+meters[k]+'</span><span>'+Math.round(a.body[k])+'</span></div><div class="track"><i style="width:'+a.body[k]+'%;background:'+(a.body[k]<25?'var(--bad)':'var(--mint)')+'"></i></div></div>').join('');
 const ac=w.activities[a.activity];$('current-activity').textContent=ac?ac.label:a.cognition.stalled?'Paused for low-benefit repetition':a.cognition.pending?'Waiting for Jev response':'No activity authorized';$('activity-source').textContent=ac?'JEV / '+ac.receipts.join(', ')+' / '+Math.ceil(ac.duration-ac.elapsed)+' min left':a.proposal?'Planner proposal available / Jev has final authority':'NO LOCAL BEHAVIOR';$('activity-progress').style.width=ac?(100*ac.elapsed/ac.duration)+'%':'0%';
 drawProfile(a);if(page!=='live'&&performance.now()-lastOverlay>1000&&!$('overlay').contains(document.activeElement)){drawPage();lastOverlay=performance.now();}if(modal==='ledger-modal'&&document.activeElement!==$('ledger-search'))drawLedger();window.OriginPanels?.afterDraw();
}
function drawProfile(a){let html='';if(tab==='story'){html=a.memory.slice(-8).reverse().map(m=>'<div class="item">'+escape(m.text)+'<small>'+escape(m.event)+' / '+Math.floor(m.time||0)+' simulated minutes</small></div>').join('');}
 if(tab==='bonds'){html=Object.entries(a.bonds).map(([id,b])=>'<div class="item"><button class="compact" data-person="'+id+'">'+humanName(id)+'</button><small>Trust '+Math.round(b.trust)+' / Affection '+Math.round(b.affection)+' / Familiarity '+Math.round(b.familiarity)+'</small></div>').join('');}
 if(tab==='family'){html='<div class="item">Partner: '+(a.partner?humanName(a.partner):'None')+'<small>Parents: '+(a.parents.map(humanName).join(', ')||'Not recorded')+'</small><small>Children: '+(a.children.map(humanName).join(', ')||'None')+'</small></div>'+(a.pregnancy?'<div class="item gold">Pregnancy recorded<small>Approx. '+Math.ceil((a.pregnancy.due-session.world.simTime)/1440)+' simulated days remaining. Simplified model; consent receipts retained.</small></div>':'');}
 if(tab==='skills'){html=Object.entries(a.known).map(([id,k])=>'<div class="item">'+escape(L.RECIPES[id]?.name||id)+'<small>Evidence '+escape(k.evidence)+' / '+escape(k.receipt||'seeded or imported')+'</small></div>').join('');if(a.knowledgeQueue.length)html+='<div class="item gold">'+a.knowledgeQueue.length+' observation(s) awaiting Jev inference.</div>';}
 if(tab==='items'){html=Object.entries(a.inventory).filter(([,n])=>n>0).map(([k,n])=>'<div class="list-row"><span>'+escape(k.replaceAll('_',' '))+'</span><b>'+n+'</b></div>').join('');}
 $('profile-content').innerHTML=html||'<p class="empty">Nothing recorded yet. This history must be lived, not fabricated.</p>';
}
function drawPage(){const w=session.world;$('overlay').hidden=page==='live';$('scene-title').hidden=page!=='live';document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='live')return;$('right').classList.remove('open');if(window.OriginPanels?.render(page,{session,selected,escape}))return;let h='';
 if(page==='people'){h='<div class="micro gold">HOUSEHOLDS / PERSONAL HISTORIES</div><h2>Everyone has a life.</h2><div class="two">'+w.households.map(x=>'<div class="card"><h3>'+escape(x.name)+'</h3><p>'+x.food+' stored food / '+x.wood+' stored wood</p>'+x.members.map(id=>'<div class="item"><button class="compact" data-person="'+id+'">'+humanName(id)+'</button><small>'+escape(L.byId(w,id)?.stage||'')+'</small></div>').join('')+'</div>').join('')+'</div><h3 style="margin-top:20px">Lives in parallel</h3>'+Object.values(w.activities).map(ac=>'<div class="item">'+humanName(ac.actor)+' / '+escape(ac.label)+'<small>'+ac.participants.map(escape).join(' + ')+' / '+Math.round(ac.elapsed)+' of '+Math.round(ac.duration)+' simulated minutes</small><div class="progress"><i style="width:'+Math.round(ac.elapsed/ac.duration*100)+'%"></i></div></div>').join('');}
 if(page==='build'){h='<div class="micro gold">PROPOSE / GATHER / BUILD / INHABIT</div><h2>A place to live.</h2><p>Choose a blueprint, then click the ground. This proposes a site; no object or resource is created. A person must choose construction through Jev and bring the materials.</p><div class="two">'+Object.entries(L.OBJECTS).map(([id,o])=>'<button class="card" data-blueprint="'+id+'"><h3>'+o.label+'</h3><div class="small">'+escape(JSON.stringify(L.objectCost(id)))+'<br>'+(o.skill?'Requires '+escape(L.RECIPES[o.skill]?.name||o.skill):'Simple assembly')+'</div></button>').join('')+'</div><h3 style="margin-top:20px">Objects in the world / '+w.objects.length+'</h3>'+w.objects.map(o=>'<div class="item">'+escape(L.OBJECTS[o.type].label)+' / '+o.id+'<small>'+o.household+' / condition '+Math.round(o.condition)+' / clean '+Math.round(o.cleanliness)+' / occupancy '+(w.locks['object:'+o.id]||[]).length+'/'+o.slots+'</small></div>').join('')+'<h3 style="margin-top:18px">Pending blueprints</h3>'+w.blueprints.filter(b=>!b.built).map(b=>'<div class="item">'+b.type+' / '+b.x+', '+b.z+'</div>').join('');}
 if(page==='world'){h='<div class="micro gold">SHARED MATERIAL WORLD</div><h2>The valley changes.</h2><p><b>'+escape(w.location.name)+'</b><br>'+escape(w.location.provenance)+'</p><canvas id="minimap" width="650" height="360" style="width:100%;border-radius:9px;background:#294233"></canvas><div class="three" style="margin-top:15px">'+Object.entries(w.resources).map(([k,n])=>'<div class="card"><h3>'+escape(k)+'</h3><span class="metric">'+Math.round(n)+'</span><div class="small">available, not already reserved</div></div>').join('')+'</div><p style="margin-top:16px">Year: '+w.settings.yearDays+' simulated days. Pregnancy: '+w.settings.gestationDays+' days. Current weather: '+w.weather+'. Weather and metabolism advance only with the authorized shared clock.</p><p class="small">These are finite synthetic deposits. They are not an inventory of Earth\'s actual resources. Planet-scale geodata and a historical Earth reconstruction are not bundled.</p>';}
 if(page==='knowledge'){h='<div class="micro gold">EVIDENCE / TRANSMISSION / MATERIAL CAPABILITIES</div><h2>What they can make.</h2><p>Knowledge is personal. Experiments require materials; each inference comes from Jev. These are bounded recipes, not a validated simulation of all physics or a guaranteed path to modern AI.</p>'+Object.entries(L.RECIPES).map(([id,r])=>{const people=w.entities.filter(a=>a.known[id]);return '<div class="tech '+(people.length?'known':'')+'"><div class="spread"><b>'+escape(r.name)+'</b><span class="micro">LEVEL '+r.tier+'</span></div><small>Requires: '+(r.requires.map(x=>escape(L.RECIPES[x]?.name||x)).join(', ')||'direct experience')+'<br>Materials: '+escape(JSON.stringify(r.material))+'<br>Known by: '+(people.map(a=>a.id).join(', ')||'nobody')+'</small></div>';}).join('')+'<h3>Learned predictor artifacts</h3>'+w.predictions.map(p=>'<div class="item">'+p.author+' / linear predictor<small>'+p.trainCount+' training and '+p.testCount+' held-out samples / MSE '+p.testMSE.toFixed(6)+'</small></div>').join('');}
 if(page==='chronicle'){h='<div class="micro gold">THINGS THAT ACTUALLY HAPPENED</div><h2>A shared history.</h2><p>These events are produced by the simulation, not written in advance. Inspect Full ledger for the provider evidence behind a voluntary action.</p>'+w.chronicle.slice(-100).reverse().map(e=>'<div class="item"><div class="micro gold">'+escape(e.kind.replaceAll('_',' '))+' / '+Math.floor(e.time)+' MIN</div><p style="margin:6px 0">'+escape(e.text)+'</p><small>'+e.id+' / '+e.people.join(', ')+'</small></div>').join('');}
 $('overlay').innerHTML=h;if(page==='world')drawMap();
}
function drawMap(){const c=$('minimap');if(!c)return;const g=c.getContext('2d'),w=session.world,to=(x,z)=>[c.width/2+x*10,c.height/2+z*5.5];g.clearRect(0,0,c.width,c.height);g.strokeStyle='#aac79822';for(let i=-25;i<=25;i+=5){g.beginPath();g.moveTo(...to(i,-25));g.lineTo(...to(i,25));g.stroke();g.beginPath();g.moveTo(...to(-25,i));g.lineTo(...to(25,i));g.stroke();}g.fillStyle='#8bb7ad55';g.fillRect(...to(16,-25),60,275);g.font='10px monospace';for(const s of Object.values(L.SITES)){const [x,y]=to(s.x,s.z);g.fillStyle='#bfc8a4';g.fillRect(x-2,y-2,4,4);g.fillText(s.name,x+5,y);}for(const o of w.objects){const [x,y]=to(o.x,o.z);g.fillStyle='#e7bb79';g.fillRect(x-4,y-4,8,8);}for(const a of w.entities){const [x,y]=to(a.x,a.z);g.fillStyle=a.id===selected?'#f9dea8':'#bde2c5';g.beginPath();g.arc(x,y,4,0,Math.PI*2);g.fill();g.fillText(a.id,x+6,y+10);}}
function drawLedger(){const q=$('ledger-search').value.trim().toLowerCase(),rows=session.log.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q)).slice(-150).reverse();$('ledger-list').innerHTML=rows.map(r=>'<button class="ledger-row" data-record="'+escape(r.id)+'"><span class="gold">'+escape(r.subject||r.event?.people?.join(', ')||'WORLD')+'</span> / '+escape(r.phase||r.event?.kind||r.type)+'<small>'+escape(r.id)+' / '+escape(r.status||'recorded')+' / '+(r.applied?'APPLIED':r.type==='request'?'NOT APPLIED':'')+'</small></button>').join('');}
// Live AI transparency: compact summaries are polled after a revision cursor while the drawer is open; a full row loads only when opened.
const AI={open:false,feed:'',rev:0,rows:new Map(),counters:null,selected:null,timer:null,busy:false,cache:new Map()};
function fmtMs(ms){return ms==null?'…':ms<1000?Math.round(ms)+' ms':ms<60000?(ms/1000).toFixed(1)+' s':(ms/60000).toFixed(1)+' min';}
function badge(s){return '<span class="ai-status '+escape(s)+'">'+escape(String(s).toUpperCase())+'</span>';}
function openAI(){AI.open=true;$('ai-drawer').hidden=false;$('right').classList.remove('open');aiPoll();clearInterval(AI.timer);AI.timer=setInterval(aiPoll,1000);}
function closeAI(){AI.open=false;$('ai-drawer').hidden=true;clearInterval(AI.timer);AI.timer=null;}
async function aiPoll(){if(!AI.open||AI.busy||document.hidden)return;AI.busy=true;try{let f=await session.aiFeed(AI.rev,300);if(f.feed!==AI.feed){AI.feed=f.feed;AI.rows=new Map();AI.rev=0;if(!f.full)f=await session.aiFeed(0,300);}
  for(const r of f.rows)AI.rows.set(r.id,r);if(AI.rows.size>1000)AI.rows=new Map([...AI.rows].sort((a,b)=>a[0]<b[0]?-1:1).slice(-1000));AI.rev=f.rev;AI.counters=f.counters;$('ai-note').textContent='Exact requests, responses, probabilities and planner audits as recorded, with keys redacted. No hidden chain-of-thought is requested or shown.';drawAI();
  if(AI.selected&&!f.full&&f.rows.some(r=>r.id===AI.selected))showAIDetail(AI.selected);}catch(e){$('ai-note').textContent=e.message;}finally{AI.busy=false;}}
function syncSelect(id,all,items){const el=$(id),value=el.value,html='<option value="">'+escape(all)+'</option>'+items.map(([v,l])=>'<option value="'+escape(v)+'">'+escape(l)+'</option>').join('');if(el.dataset.html!==html){el.innerHTML=html;el.dataset.html=html;el.value=value;}}
function drawAI(){const c=AI.counters;if(c){const stop=c.stop?'<div style="grid-column:1/-1;border-color:var(--bad)"><span class="micro" style="color:var(--bad)">STOPPED / '+escape(c.stop.kind==='planner'?'PLANNER BUDGET':c.stop.kind==='jev'?'JEV BUDGET':'RUN WINDOW')+'</span><b>'+escape(c.stop.text)+'</b></div>':'';const j=c.jev,p=c.planner;$('ai-counters').innerHTML=[['Jev calls',j.ok+' ok / '+(j.rejected+j.error)+' failed'+(j.pending?' / '+j.pending+' pending':'')],['Planner calls',p.ok+' ok / '+p.rejected+' rejected / '+p.error+' error'+(p.pending?' / '+p.pending+' pending':'')],['Tokens',Number(c.tokens||0).toLocaleString()],['Total latency',fmtMs(c.latencyMs)],['Jev budget',c.budget.jev+' / '+c.budget.jevCap+(c.costKnown?' / $'+Number(c.cost).toFixed(4):'')],['Planner budget',c.budget.planner+' / '+c.budget.plannerCap]].map(([k,v])=>'<div><span class="micro quiet">'+escape(k)+'</span><b>'+escape(v)+'</b></div>').join('')+stop;}
 const rows=[...AI.rows.values()];syncSelect('ai-engine','All engines',[...new Set(rows.map(r=>r.engine))].sort().map(e=>[e,e]));syncSelect('ai-person','Everyone',[...new Map(rows.filter(r=>r.subject).map(r=>[r.subject,(r.name?r.name+' ':'')+r.subject]))].sort());
 const engine=$('ai-engine').value,status=$('ai-status').value,person=$('ai-person').value,list=rows.filter(r=>(!engine||r.engine===engine)&&(!status||r.status===status)&&(!person||r.subject===person)).sort((a,b)=>a.id<b.id?1:-1).slice(0,300);
 $('ai-list').innerHTML=list.map(r=>'<button class="ai-row" data-ai="'+escape(r.id)+'">'+badge(r.status)+'<b>'+escape(r.engine)+'</b> / '+escape(r.phase)+(r.subject?' / '+(r.name?escape(r.name)+' ':'')+'<span class="quiet">'+escape(r.subject)+'</span>':'')+'<span class="headline">'+escape(r.headline)+(r.confidence!=null?' ('+Math.round(r.confidence*100)+'% confidence)':'')+'</span><small>'+escape([r.id,r.at?new Date(r.at).toLocaleTimeString():'',r.model,'latency '+fmtMs(r.latencyMs),r.tokens?r.tokens+' tokens':'',r.applied?'applied':r.notApplied?'not applied':'',r.matched===true?'followed the planner':r.matched===false?'differed from the planner':'',r.truncated?'truncated for storage':''].filter(Boolean).join(' / '))+'</small></button>').join('')||'<p class="empty">No Jev or planner call recorded yet. Each call appears here the moment it is sent.</p>';}
async function showAIDetail(id){AI.selected=id;const row=await guarded(()=>session.aiRow(id));if(!row){toast('Record '+id+' is not available.');return;}AI.cache.set(row.id,row);renderDetail($('ai-detail'),row);$('ai-list').hidden=true;$('ai-detail-pane').hidden=false;}
function backAI(){AI.selected=null;$('ai-detail-pane').hidden=true;$('ai-list').hidden=false;}
function renderDetail(el,row){const open=[...el.querySelectorAll('details')].map(d=>d.open);el.innerHTML=aiDetailHTML(row);el.querySelectorAll('details').forEach((d,i)=>{if(open[i])d.open=true;});}
function copyRow(id){const row=AI.cache.get(id);if(!row)return;const text=JSON.stringify(row,null,2);(navigator.clipboard?navigator.clipboard.writeText(text):Promise.reject()).then(()=>toast('Copied '+id+' as JSON.'),()=>download(id+'.json',text));}
function pre(v){return '<pre>'+escape(typeof v==='string'?v:JSON.stringify(v,null,2))+'</pre>';}
function section(title,v,open){return v==null||v===''||(Array.isArray(v)&&!v.length)?'':'<details'+(open?' open':'')+'><summary>'+escape(title)+'</summary>'+pre(v)+'</details>';}
function aiDetailHTML(row){if(!row)return '<p class="empty">Record not found.</p>';const LS=window.LivingSession,copy='<button class="compact" data-copy="'+escape(row.id)+'">Copy JSON</button>';
 if(!LS.aiKind(row))return '<div class="spread"><b>'+escape(row.type)+' / '+escape(row.id)+'</b>'+copy+'</div>'+pre(row);
 const d=LS.aiDetail(row),s=d.summary;let h='<div class="spread"><div>'+badge(s.status)+'<b>'+escape(s.engine)+'</b> <span class="quiet">'+escape(s.model||'model not reported')+'</span></div>'+copy+'</div>';
 h+='<div class="ai-meta">'+escape([row.id,s.at?new Date(s.at).toLocaleString():'',s.subject?(s.name||L.byId(session.world,s.subject)?.observerName||'')+' '+s.subject:'',s.phaseText,s.cohort!=null?'cohort '+s.cohort:'','latency '+fmtMs(s.latencyMs),s.tokens?s.tokens+' tokens':'',s.cost!=null?'$'+Number(s.cost).toFixed(5):'',d.httpStatus?'HTTP '+d.httpStatus:'',d.providerRequestId?'provider request '+d.providerRequestId:''].filter(x=>String(x).trim()).join(' / '))+'</div>';
 if(d.error)h+='<p class="ai-error">'+escape(d.error)+'</p>';
 h+='<p class="small">'+(d.applied.applied?'Applied to <b>'+escape(d.applied.activity)+'</b>.':d.applied.notApplied?escape(d.applied.notApplied):s.status==='pending'?'In progress: sent, waiting for the response.':'Not applied.')+(d.validation?' Validation: '+(d.validation.valid?'passed'+(d.validation.questions?' ('+d.validation.questions+' questions'+(d.validation.gate?', confidence gate '+d.validation.gate:'')+')':''):'failed at '+escape(d.validation.stage)+': '+escape(d.validation.reason)):'')+'</p>';
 const trunc=d.truncated||d.planner?.truncated;if(trunc)h+='<p class="small gold">Truncated for storage (original size in characters): '+escape(Object.entries(trunc).map(([k,n])=>k+' '+n).join(', '))+'.</p>';
 if(d.kind==='jev'){if(d.plannerProposal)h+='<p class="small">Planner proposal '+escape(d.plannerProposal.receipt)+' suggested '+escape(d.plannerProposal.actions.join(', ')||'nothing')+'. Jev\'s choice '+(d.plannerProposal.matched?'<b class="gold">followed it</b>':'<b>differed</b>')+'.</p>';
  for(const q of d.questions)h+='<div class="aiq"><div class="spread"><span class="micro gold">QUESTION / '+escape(q.id)+'</span><span class="micro">'+(q.confidence!=null?'CONFIDENCE '+(q.confidence*100).toFixed(1)+'%':'NO ANSWER')+'</span></div><p>'+escape(q.instructions)+'</p>'+q.options.map(o=>'<div class="aiopt'+(o.chosen?' chosen':'')+'"><span>'+(o.chosen?'&#10003; ':'')+'<b>'+escape(o.id)+'</b> / '+escape(o.label)+'</span><span class="bar"><i style="width:'+(o.p==null?0:Math.max(0,Math.min(100,o.p*100))).toFixed(1)+'%"></i></span><span class="pct">'+(o.p==null?'n/a':(o.p*100).toFixed(1)+'%')+'</span></div>').join('')+'</div>';
  return h+section('Perception / state sent to Jev',d.state)+section('Raw request (exact body)',d.raw.request)+section('Raw response',d.raw.response)+section('Usage',d.usage);}
 const p=d.planner;h+='<div class="aiq"><div class="micro gold">VERDICT</div><p>'+(p.verdict?(p.verdict.accepted?'<b class="gold">Accepted</b> as an unverified proposal. Jev still decides.':'<b>Rejected</b> at '+escape(p.verdict.stage)+'.')+(p.verdict.reason&&!p.verdict.accepted?' '+escape(p.verdict.reason):''):'Pending.')+'</p>';
 if(p.proposal){const pr=p.proposal;h+='<p><b>Objective:</b> '+escape(pr.objective)+'<br><b>Hypothesis:</b> '+escape(pr.hypothesis)+'<br><b>Proposed actions:</b> '+escape((pr.actions||[]).map(a=>a+(p.actionLabels[a]?' ('+p.actionLabels[a]+')':'')).join(', '))+'<br><b>Expected observation:</b> '+escape(pr.expectedObservation)+'<br><b>Evidence:</b> '+escape((pr.evidence||[]).join(', ')||'none cited')+(pr.utterance?'<br><b>Utterance to '+escape(pr.utterance.to)+':</b> &ldquo;'+escape(pr.utterance.text)+'&rdquo;':'')+'</p>';}
 if(p.jevChoices.length)h+='<p class="small">Jev decisions made with this proposal: '+p.jevChoices.map(c=>escape(c.receipt)+' &rarr; '+escape(c.action)+' ('+(c.matched?'followed':'differed')+')').join('; ')+'</p>';
 return h+'</div>'+section('Exact prompt sent',p.prompt)+section('CLI command and arguments',p.command?{command:p.command,args:p.args,workingDirectory:p.workingDirectory,policy:p.policy}:null)+section('HTTP endpoint and request body',p.endpoint?{endpoint:p.endpoint,request:p.request}:null)+section('Event stream ('+(p.events?.length||0)+' events)',p.events)+section('stderr',p.stderr)+section('Raw output',p.output)+section('Perception sent to the planner',d.state)+section('Raw planner response (proposal + audit)',d.raw.response);}
// Budgets are explicit: usage beside each field, a next value only prefilled (never applied) when a limit is used up.
function nextLimit(used,limit,step,max){return limit>used?limit:Math.min(max,used+step);}
function budgetFields(){const s=session,c=s.config,stop=s.state==='budget'?s.budgetStop:null,planner=c.planner!=='none';$('budget-summary').textContent='Jev decisions: '+s.attempts+' / '+c.cap+' used ('+Math.max(0,c.cap-s.attempts)+' left). Planner proposals: '+s.plannerAttempts+' / '+c.plannerCap+' used ('+Math.max(0,c.plannerCap-s.plannerAttempts)+' left'+(planner?', planner: '+c.planner:', planner off')+'). '+(s.costKnown?'Provider-reported Jev cost so far: $'+s.cost.toFixed(5)+'.':'Cost not reported by this provider.')+' Historical attempts count toward both totals.';
 $('budget-stop').hidden=!stop;$('budget-stop').textContent=stop?.text||'';$('budget-jev-used').textContent='/ '+s.attempts+' used';$('budget-planner-used').textContent='/ '+s.plannerAttempts+' used';$('budget-jev').min=Math.max(1,s.attempts);$('budget-planner').min=Math.max(1,s.plannerAttempts);
 $('budget-jev').value=stop?.kind==='jev'?Math.min(100000,Math.max(c.cap,s.attempts+500)):nextLimit(s.attempts,c.cap,500,100000);$('budget-planner').value=stop?.kind==='planner'?Math.min(10000,Math.max(c.plannerCap,s.plannerAttempts+100)):nextLimit(s.plannerAttempts,c.plannerCap,100,10000);$('budget-jev-only').hidden=!planner;}
function connectionFields(){const c=session.config;$('provider').value=c.provider;$('model').innerHTML=P.get(c.provider).models.map(m=>'<option value="'+m.id+'">'+m.label+'</option>').join('');$('model').value=c.model;$('transport').value=c.transport;$('transport').disabled=!!session.isRemote;$('planner').value=c.planner;$('jev-cap').value=nextLimit(session.attempts,c.cap,500,100000);$('jev-used').textContent='/ '+session.attempts+' used';$('planner-used').textContent='/ '+session.plannerAttempts+' used';$('jev-cap').min=Math.max(1,session.attempts+1);$('jev-cap').title='Already attempted: '+session.attempts+'. Enter an explicitly authorized total greater than this count.';$('planner-cap').value=nextLimit(session.plannerAttempts,c.plannerCap,100,10000);$('parallel').value=c.parallelCalls;$('planner-model').value=c.plannerModel;$('key-status').textContent=session.bridgeInfo?'Local bridge ready. TypeSafe key: '+(session.bridgeInfo.hasTypeSafeKey?'configured':'not configured')+'. Cloud planner: '+(session.bridgeInfo.cloudEnabled?'configured':'not configured')+'. agy: '+(session.bridgeInfo.agyEnabled?'enabled':'disabled')+'. OpenAI-compatible / local LLM: '+(session.bridgeInfo.llmStatus||'not configured')+(session.bridgeInfo.llmModel?' ('+session.bridgeInfo.llmModel+')':'')+'. Claude Code: '+(session.bridgeInfo.claudeEnabled?'enabled':'disabled')+'. Codex: '+(session.bridgeInfo.codexEnabled?'enabled':'disabled')+'.':'No local bridge. Use the included server for .env credentials and planners.';}
function connectConfig(){return {provider:$('provider').value,model:$('model').value,transport:$('transport').value,planner:$('planner').value,plannerModel:$('planner-model').value.trim(),cap:Number($('jev-cap').value),plannerCap:Number($('planner-cap').value),parallelCalls:Number($('parallel').value),rate:Number($('speed').value)};}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close!==undefined)close();if(b.dataset.person)choose(b.dataset.person);if(b.dataset.page){page=b.dataset.page;drawPage();}if(b.dataset.tab){tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));draw();}if(b.dataset.camera){view?.mode(b.dataset.camera);}if(b.dataset.blueprint){buildType=b.dataset.blueprint;page='live';drawPage();toast('Click an accessible place in the valley to propose a '+buildType+'.');}if(b.dataset.record){const r=session.log.find(r=>r.id===b.dataset.record);if(r){AI.cache.set(r.id,r);renderDetail($('ledger-detail'),r);}}if(b.dataset.ai)showAIDetail(b.dataset.ai);if(b.dataset.copy)copyRow(b.dataset.copy);});
$('ai-btn').onclick=()=>AI.open?closeAI():openAI();$('ai-close').onclick=closeAI;$('ai-back').onclick=backAI;for(const id of ['ai-engine','ai-status','ai-person'])$(id).onchange=drawAI;
$('connect-btn').onclick=()=>show('connect-modal');$('help-btn').onclick=()=>show('help-modal');$('loading-help').onclick=()=>show('help-modal');$('budget-btn').onclick=()=>show('budget-modal');$('ledger-btn').onclick=()=>show('ledger-modal');$('suggest-btn').onclick=()=>show('suggest-modal');$('retry-render').onclick=()=>initView(session.world);
$('run-btn').onclick=()=>guarded(()=>session.running?session.pause():session.connected?session.start():show('connect-modal'));$('wave-btn').onclick=()=>guarded(()=>session.connected?session.start(true):show('connect-modal'));$('speed').onchange=()=>{guarded(async()=>{session.config.rate=Number($('speed').value);await session.record('time_scale',{minutesPerSecond:session.config.rate});});};$('review-btn').onclick=()=>guarded(()=>session.review());
$('save-btn').onclick=()=>guarded(async()=>{await session.checkpoint();download('ORIGIN-civilization.save.json',session.isRemote?await session.fullExport():session.export());toast('World, activities, memories and audit exported. Credentials excluded.');});$('photo-btn').onclick=()=>guarded(()=>{const data=view.capture(),a=document.createElement('a');a.href=data;a.download='ORIGIN-living-world.png';a.click();});$('follow-btn').onclick=()=>view?.mode('follow');$('mobile-person').onclick=()=>$('right').classList.toggle('open');$('close-profile').onclick=()=>$('right').classList.remove('open');$('cinema-btn').onclick=()=>document.body.classList.toggle('cinema');$('cutaway-btn').onclick=()=>{if(view){view.cutaway=!view.cutaway;view.sync(session.world);}};
$('connection-form').onsubmit=async e=>{e.preventDefault();$('connection-error').textContent='';try{await session.connect($('api-key').value,connectConfig());session.allowDetached=$('detached-run').checked;session.runMinutes=Number($('run-window').value);$('api-key').value='';close();await session.start();}catch(err){$('connection-error').textContent=err.message;toast(err.message);}};
$('provider').onchange=()=>{const p=P.get($('provider').value);$('model').innerHTML=p.models.map(m=>'<option value="'+m.id+'">'+m.label+'</option>').join('');};
$('access-btn').onclick=async()=>{try{session.config.transport=$('transport').value;session.config.provider=$('provider').value;await session.accessCheck($('api-key').value);$('connection-error').textContent='TypeSafe model-list access succeeded. No action was executed.';}catch(e){$('connection-error').textContent=e.message;}};
$('budget-jev-only').onclick=()=>guarded(async()=>{const jev=Number($('budget-jev').value),planner=Math.max(session.plannerAttempts,Number($('budget-planner').value)||session.config.plannerCap);await session.budget(jev,planner);await session.connect('',{...session.config,planner:'none',cap:jev,plannerCap:planner});close();toast('Planner turned off for this run; Jev decides alone. Press Run lives to resume.');});
$('budget-form').onsubmit=e=>{e.preventDefault();guarded(async()=>{await session.budget($('budget-jev').value,$('budget-planner').value);close();toast('Limits updated. Press Run lives to resume.');});};
$('suggest-form').onsubmit=e=>{e.preventDefault();guarded(async()=>{const text=$('suggest-text').value.trim().slice(0,600);if(session.isRemote)await session.command('suggest',{subject:selected,text});else{const a=L.byId(session.world,selected);a.activeSuggestion=text;session.record('player_suggestion',{subject:a.id,text,notice:'Unverified suggestion, not an executed command.'});}close();toast('Included in '+selected+"'s next decision context.");});};
$('first-minds-btn').onclick=()=>guarded(async()=>{if(confirm('Replace the current world with six first minds? Save first to retain it. API usage is not reset.')){await session.reset('first-minds');close();}});$('homestead-btn').onclick=()=>guarded(async()=>{if(confirm('Replace the world with a declared seeded household scenario? Save first to retain the current world.')){await session.reset('homestead');close();}});
$('life-scale-form').onsubmit=e=>{e.preventDefault();guarded(async()=>{const y=Number($('year-days').value),g=Number($('gestation-days').value);if(!Number.isFinite(y)||y<1||y>365||!Number.isFinite(g)||g<1||g>280)throw Error('Invalid life scale.');if(session.isRemote)await session.command('lifeScale',{yearDays:y,gestationDays:g});else{session.world.settings.yearDays=y;session.world.settings.gestationDays=g;session.record('life_scale',{yearDays:y,gestationDays:g,notice:'Declared biological abstraction.'});}toast('Declared life scale updated.');});};
$('load-btn').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;await guarded(async()=>{if(f.size>64*1024*1024)throw Error('Save exceeds 64 MB.');await session.restore(JSON.parse(await f.text()));close();});e.target.value='';};$('checkpoint-btn').onclick=()=>guarded(async()=>{await session.loadCheckpoint();close();});$('recovery-btn').onclick=()=>guarded(async()=>{await session.loadCheckpoint('/api/recovery');close();toast('Supplied civilization restored in pause. 961 historical calls retained; no new budget authorized. Inspect Life audit, then connect.');});
$('ledger-search').oninput=drawLedger;$('export-ledger').onclick=()=>guarded(async()=>{const log=session.isRemote?await session.fullLedger():session.log;download('ORIGIN-v6-decision-ledger.jsonl',log.map(r=>JSON.stringify(r)).join('\n')+'\n','application/x-ndjson');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const hadModal=!!modal;close();$('right').classList.remove('open');buildType=null;if(!hadModal&&AI.open)closeAI();}if(modal&&e.key==='Tab'){const focus=[...$(modal).querySelectorAll('button,input,select,textarea,summary')].filter(n=>!n.disabled&&n.offsetParent!==null);if(e.shiftKey&&document.activeElement===focus[0]){e.preventDefault();focus.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===focus.at(-1)){e.preventDefault();focus[0]?.focus();}}if(modal||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('run-btn').click();}if(e.key.toLowerCase()==='f')document.body.classList.toggle('cinema');});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session.running&&!session.isRemote)session.pause('Tab hidden: shared time and new requests paused.');});window.addEventListener('origin-render-failure',e=>{if(view?.disableThree)view.disableThree();toast('3D display stopped. The isometric view shows the same world. '+e.detail);});
session.bootstrap().then(()=>{connectionFields();schedule();}).catch(e=>{if(!session.isRemote)session.config.transport='direct';else{session.error=e.message;session.state='offline';}connectionFields();toast(e.message);});initView(session.world);draw();setInterval(()=>{if(!document.hidden)draw();},550);
})();
