'use strict';
const zlib=require('node:zlib');
/* Minimal audited PNG decoder for public 8-bit RGB/RGBA Terrarium tiles.
   No user-supplied URL: one allowlisted public elevation bucket only. */
function png(buffer){if(!Buffer.isBuffer(buffer)||buffer.length>2000000||buffer.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Not a bounded PNG tile.');let at=8,width,height,bpp,parts=[];
 while(at+12<=buffer.length){const n=buffer.readUInt32BE(at),type=buffer.subarray(at+4,at+8).toString('ascii');if(at+n+12>buffer.length)throw Error('Truncated PNG.');const data=buffer.subarray(at+8,at+8+n);if(type==='IHDR'){width=data.readUInt32BE(0);height=data.readUInt32BE(4);const depth=data[8],color=data[9];if(depth!==8||![2,6].includes(color)||data[12]!==0||width>512||height>512)throw Error('Unsupported elevation PNG format.');bpp=color===2?3:4;}if(type==='IDAT')parts.push(data);at+=n+12;if(type==='IEND')break;}
 if(!width||!height||!parts.length)throw Error('Missing PNG data.');const stride=width*bpp,raw=zlib.inflateSync(Buffer.concat(parts),{maxOutputLength:(stride+1)*height}),out=Buffer.alloc(stride*height);if(raw.length!==(stride+1)*height)throw Error('Unexpected decompressed PNG size.');const paeth=(a,b,c)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};
 for(let y=0;y<height;y++){const f=raw[y*(stride+1)];if(f>4)throw Error('Unknown PNG filter.');for(let x=0;x<stride;x++){const a=x>=bpp?out[y*stride+x-bpp]:0,b=y?out[(y-1)*stride+x]:0,c=y&&x>=bpp?out[(y-1)*stride+x-bpp]:0;const n=raw[y*(stride+1)+1+x];out[y*stride+x]=(n+(f===1?a:f===2?b:f===3?Math.floor((a+b)/2):f===4?paeth(a,b,c):0))&255;}}
 return {width,height,elevation:(x,y)=>{const i=(y*width+x)*bpp;return out[i]*256+out[i+1]+out[i+2]/256-32768;}};
}
function tileFor(lat,lon,z=12){if(!Number.isFinite(lat)||lat<-80||lat>80||!Number.isFinite(lon)||lon<-180||lon>180)throw Error('Unsupported coordinate.');const n=2**z;return {z,x:Math.min(n-1,Math.floor((lon+180)/360*n)),y:Math.min(n-1,Math.floor((1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*n))};}
async function load(lat,lon,{fetchImpl=fetch,signal}={}){lat=Number(lat);lon=Number(lon);const t=tileFor(lat,lon),url='https://s3.amazonaws.com/elevation-tiles-prod/terrarium/'+t.z+'/'+t.x+'/'+t.y+'.png';const r=await fetchImpl(url,{signal,redirect:'error'});if(!r.ok)throw Error('Elevation source HTTP '+r.status);const b=Buffer.from(await r.arrayBuffer());const im=png(b),values=[];for(let j=0;j<33;j++)for(let i=0;i<33;i++)values.push(+im.elevation(Math.round(i*(im.width-1)/32),Math.round(j*(im.height-1)/32)).toFixed(2));const n=2**t.z,lonW=t.x/n*360-180,lonE=(t.x+1)/n*360-180,toLat=y=>Math.atan(Math.sinh(Math.PI*(1-2*y/n)))*180/Math.PI;return {values,grid:33,bounds:{west:lonW,east:lonE,north:toLat(t.y),south:toLat(t.y+1)},source:url,sourceName:'Mapzen Terrain Tiles / underlying source attribution retained',attribution:'Mapzen; USGS; NOAA. See docs/DATA-SOURCES.md.',sampledAt:new Date().toISOString(),metresPerUnit:((40075016.686/n)*Math.cos(lat*Math.PI/180))/96,notice:'Actual sampled elevation. Horizontal area is compressed into a 96-unit gameplay region. Water, biology and deposits are NOT supplied by this elevation tile.'};}
module.exports={load,png,tileFor};
